### ISSUE TITLE
[FEATURE] - Inspect/View a vote file

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#11]
## What

As an CCMember, Drep or SPO  I want to inspect/view the content of a vote file 
so that I can verify its content before submitting it to the chain. 

The command should be something like:

```
cardano-cli conway governance vote view --vote-file FILE
```

## Why

Creating the vote and submitting it to the chain involves a number of sequential steps.  We need to be able to inspect the contents of any artifact produced or used during the process. 

## Personas

- [x] Constitutional committee members
- [x] Delegate representatives
- [x] SPOs
- [ ] dApp Devs
- [ ] Exchanges
- [ ] Wallets
- [ ] 3rd party tools
- [ ] ADA holders 

## Acceptance Criteria

- [ ] The command should accept the `--vote-file` flag, which specifies the file containing the vote to be inspected.
- [ ] Running the command without providing the `--vote-file` flag should result in an appropriate error message indicating that the flag is required.
- [ ] The command should display the content of the vote file, including relevant information such as the voter's verification key, role, action ID, vote choice, and any additional metadata.
- [ ] The displayed content should be presented in a clear and readable format, ensuring that users can easily review and verify the information.
- [ ] The command should handle potential errors, such as missing or invalid vote files, and provide informative error messages or exceptions when necessary.
- [ ] The command should be documented in the CLI usage, describing its purpose, available flags, and expected inputs and outputs.

## Definition of Done (DoD)

- [ ] [Acceptance Criteria + User Stories & DoD](https://input-output.atlassian.net/wiki/spaces/QA/pages/3584229468/Acceptance+Criteria+DoD) created and singed-off (by PO, dev & test owners)
- [ ] Builds successfully on CI
- [ ] Code & Test review (as per Acceptance Criteria)
- [ ] There is documentation and/or examples for the new functionality (usage/response)
- [ ] Log/record changes on **Vnext** (or similar depending on what we adopt)
- [ ] Ticket number(s) included in PR description
- [ ] All Acceptance Criteria met and covered by dev/unit/property/integration tests
- [ ] System/E2E automated tests + System Test Engineer Owner Sign-off

# Sign-off

- [ ] Product Owner
- [ ] Dev Owner
- [ ] System Test Engineer Owner

> **_NOTE:_**  Ideally, we should merge only fully implemented and tested features into the master branch. 
> So all the above steps are required for the PR to be merged.  
> In order to avoid the PRs becoming stale and requiring to be rebased on master, these can be merged 
> after a reasonable time (current agreement is 3 days) if the System Test Engineer Owner's sign-off 
> was not provided (last step in the DoD).

> **_IMPORTANT:_** Any deviation from the plan should be discussed and agreed as a comment in the Feature file. 

## Related PRs

**Comment by rdlrt** [comment]
.
