### ISSUE TITLE
[FEATURE] - Modify BUILD-RAW command to take vote and action files to build a transaction body

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#12]
## What

As a CC Member, Drep, SPO or Ada Holder I want to build a transaction body that includes governance actions and votes on governance actions. So that I can submit an action or vote to the chain. 

So we need `build-raw` to have two new flags:

```
cardano-cli transaction build-raw 
[--proposal-file FILE] 
[--vote-file FILE]
```
 
## Why

Without this feature users would not be able to submit governance actions or votes to the chain. 

## Personas

- [x] Constitutional committee members
- [x] Delegate representatives
- [x] SPOs
- [ ] dApp Devs
- [ ] Exchanges
- [ ] Wallets
- [ ] 3rd party tools
- [ ] ADA holders 

## Acceptance Criteria

- [ ] The cardano-cli transaction build-raw command should be enhanced to include two new flags: --action-file and --vote-file.The --action-file flag should specify the file containing the governance action to be included in the transaction body.
- [ ] The --vote-file flag should specify the file containing the vote to be included in the transaction body.
- [ ] Running the build-raw command without providing the --action-file or --vote-file flags should not result in an error
- [ ] The transaction building process should handle the inclusion of governance actions and votes correctly, ensuring that they are properly formatted and integrated into the transaction body.
- [ ] The built transaction body should adhere to the Cardano transaction format and include the specified governance actions and votes.
- [ ] The command should handle potential errors, such as missing or invalid action or vote files, and provide informative error messages or exceptions when necessary.
- [ ] The command should be documented in the CLI usage, describing its purpose, available flags, and expected inputs and outputs.

## Definition of Done (DoD)

- [ ] [Acceptance Criteria + User Stories & DoD](https://input-output.atlassian.net/wiki/spaces/QA/pages/3584229468/Acceptance+Criteria+DoD) created and singed-off (by PO, dev & test owners)
- [ ] Builds successfully on CI
- [ ] Code & Test review (as per Acceptance Criteria)
- [ ] There is documentation and/or examples for the new functionality (usage/response)
- [ ] Log/record changes on **Vnext** (or similar depending on what we adopt)
- [ ] Ticket number(s) included in PR description
- [ ] All Acceptance Criteria met and covered by dev/unit/property/integration tests
- [ ] System/E2E automated tests + System Test Engineer Owner Sign-off

# Sign-off

- [ ] Product Owner
- [ ] Dev Owner
- [ ] System Test Engineer Owner

> **_NOTE:_**  Ideally, we should merge only fully implemented and tested features into the master branch. 
> So all the above steps are required for the PR to be merged.  
> In order to avoid the PRs becoming stale and requiring to be rebased on master, these can be merged 
> after a reasonable time (current agreement is 3 days) if the System Test Engineer Owner's sign-off 
> was not provided (last step in the DoD).

> **_IMPORTANT:_** Any deviation from the plan should be discussed and agreed as a comment in the Feature file. 

## Related PRs

**Comment by carlhammann** [comment]
It seems this is already implemented, as of #365
