### ISSUE TITLE
`governance` commands missing from CLI

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-cli#122]
## Description

Governance commands are missing from CLI. The only command that is available is `pre-conway` that doesn't have any sub-commands or arguments.

## Steps to Reproduce

1.
```
$ cardano-cli governance update-proposal
Invalid argument `update-proposal'

Usage: cardano-cli governance pre-conway

  Era-based governance commands
```

## Additional Context

This behavior is present in CLI that's part of node 8.2.0-pre release and in current node master (`408d8ae10a2792ace3a822e312433960e47de4e9`).

**Comment by carbolymer** [comment]
Related pr: https://github.com/input-output-hk/cardano-cli/pull/124

**Comment by mkoura** [comment]
Already fixed.
