### ISSUE TITLE
[FEATURE] - DREP key generation

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#128]
## What

Implement drep key generation for the [case of Ed25519 keys. ](https://github.com/cardano-foundation/CIPs/blob/e96681908fd336702b9d89827063a190c5656eab/CIP-1694/README.md?plain=1#LL378C1-L379C28)
It should be something like: 

```
cardano-cli conway governance drep key-gen 
--verification-key-file FILE 
--signing-key-file FILE
```

## Why

In Voltaire, existing stake credentials will be able to delegate their stake to registered DReps for voting purposes,
in addition to the current delegation to stake pools for block production.

DRep delegation will mimic the existing stake delegation mechanisms (via on-chain certificates).
Similarly, DRep registration will mimic the existing stake registration mechanisms.

## Personas

- [] Constitutional committee members
- [x] Delegate representatives
- [ ] SPOs
- [ ] dApp Devs
- [ ] Exchanges
- [ ] Wallets
- [ ] 3rd party tools
- [x] ADA holders 

## Acceptance Criteria

1. The `cardano-cli conway governance drep key-gen` command should be available and functional.
2. The feature implementation should be well-documented, with clear instructions on how to use the cardano-cli conway governance drep key-gen command.
3. The command should support the `--verification-key-file FILE` option to specify the file where the generated verification key will be saved.
4. The command should support the `--signing-key-file FILE` option to specify the file where the generated signing key will be saved.
5. When the command is executed, it should generate both the verification key and signing key for DRep key generation.
6. Files should be saved on the specified path
7. The key generation should follow the current design for key generation and output in an envelope format like the following:

```
{
 "type": "DRepVerificationKey_ed25519",
 "description": "Delegate Representative Verification Key",
  "cborHex": "00000"
}
```
8. The generated keys should be compatible with the DRep delegation and registration mechanisms as described in the "Why" section of the feature request.
9. The feature should be thoroughly tested to ensure the correctness of key generation

## Definition of Done (DoD)

- [ ] [Acceptance Criteria + User Stories & DoD](https://input-output.atlassian.net/wiki/spaces/QA/pages/3584229468/Acceptance+Criteria+DoD) created and singed-off (by PO, dev & test owners)
- [ ] Builds successfully on CI
- [ ] Code & Test review (as per Acceptance Criteria)
- [ ] There is documentation and/or examples for the new functionality (usage/response)
- [ ] Log/record changes on **Vnext** (or similar depending on what we adopt)
- [ ] Ticket number(s) included in PR description
- [ ] All Acceptance Criteria met and covered by dev/unit/property/integration tests
- [ ] System/E2E automated tests + System Test Engineer Owner Sign-off

# Sign-off

- [ ] Product Owner
- [ ] Dev Owner
- [ ] System Test Engineer Owner

> **_NOTE:_**  Ideally, we should merge only fully implemented and tested features into the master branch. 
> So all the above steps are required for the PR to be merged.  
> In order to avoid the PRs becoming stale and requiring to be rebased on master, these can be merged 
> after a reasonable time (current agreement is 3 days) if the System Test Engineer Owner's sign-off 
> was not provided (last step in the DoD).

> **_IMPORTANT:_** Any deviation from the plan should be discussed and agreed as a comment in the Feature file. 

## Related PRs

**Comment by gitmachtl** [comment]
> Acceptance Criteria

The keys should also be accepted if of type ed25519e, directly derived from mnemonics and/or path `1852'/1815'/acc'/3/index` according to the new [CIP95](https://github.com/cardano-foundation/CIPs/pull/509). See the suggested keyType at the end of the post.

The keyType and description should be in line if possible, currently in CIP95 this is:

Examples of acceptable `keyType`s for supporting tools:

| `keyType`                          | Description           |
| ---------------------------------- | --------------------- |
| `CIP95DRepSigningKey_ed25519`      | DRep Signing Key      |
| `CIP95DRepVerificationKey_ed25519` | DRep Verification Key |

For hardware implementations:

| `keyType`                          | Description                    |
| ---------------------------------- | ------------------------------ |
| `CIP95DRepVerificationKey_ed25519` | Hardware DRep Verification Key |
| `CIP95DRepHWSigningFile_ed25519`   | Hardware DRep Signing File     |

So it would be good to bring the CIP95 and/or the suggested key type/description in line so its the same. 🙏 Most likely just dropping the CIP95 prefix?

And as discussed with @disassembler , it would make sense to align the type for the derived keys with the ones we already have for payment, stake, ... 

So a dRep key could have the type `DRepExtendedSigningKey_ed25519_bip32`

**Comment by gitmachtl** [comment]
```console
cardano-signer keygen --path drep --json-extended
or
cardano-signer keygen --path 1852H/1815H/0H/3/0 --json-extended
```
```json
{
  "workMode": "keygen",
  "path": "1852H/1815H/0H/3/0",
  "mnemonics": "draw fold panda deliver robot response skin session print urge broccoli ethics adult solve volcano leave reunion orient neglect unaware champion flock oyster skirt",
  "secretKey": "c084e98f38c5566e224d6e6bc380a67202b73e39aa503ec3f720abbd9609a05d2e1520628d58dbd0946b1ff734f705797d587eef5144216c05ce6e983b8ffe22",
  "publicKey": "51dfa5f427777c1157526537cef650daae477fe4c07652d52aeb53c45126d2a0",
  "XpubKeyHex": "f286ef6433e2db3a1e4b4038173d45dff72815fdd7cefa054d2f5063324b2b6387d39760d21de7d54b20ba31bf70e7cee029352123c7bc4867630b37110faa89",
  "XpubKeyBech": "xpub172rw7epnutdn58jtgqupw029mlmjs90a6l805p2d9agxxvjt9d3c05uhvrfpme74fvst5vdlwrnuacpfx5sj83aufpnkxzehzy864zgj39qvs",
  "drepIdHex": "eb28c5aa02da9c8f958a6f48d18c7523faf51786686541ef949529bb",
  "drepIdBech": "drep_id1av5vt2szm2wgl9v2daydrrr4y0a029uxdpj5rmu5j55mkejadea",
  "secretKeyBech": "drep_sk1czzwnrecc4txugjdde4u8q9xwgptw03e4fgraslhyz4mm9sf5pwju9fqv2x43k7sj343lae57uzhjl2c0mh4z3ppdszuum5c8w8lugslff9x3",
  "publicKeyBech": "drep_vk12806tap8wa7pz46jv5muaajsm2hywllycpm994f2adfug5fx62sqe7m6xt",
  "output": {
    "skey": {
      "type": "DRepExtendedSigningKey_ed25519_bip32",
      "description": "Delegate Representative Signing Key",
      "cborHex": "5840c084e98f38c5566e224d6e6bc380a67202b73e39aa503ec3f720abbd9609a05d2e1520628d58dbd0946b1ff734f705797d587eef5144216c05ce6e983b8ffe22"
    },
    "vkey": {
      "type": "DRepExtendedVerificationKey_ed25519_bip32",
      "description": "Delegate Representative Verification Key",
      "cborHex": "582051dfa5f427777c1157526537cef650daae477fe4c07652d52aeb53c45126d2a0"
    }
  }
}
```
