### ISSUE TITLE
[FEATURE] - command to create Drep registration certificate

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#131]
## What

Implement a command to generate DRep registration certificate. This certificate will later be included on a transaction body to submit it on-chain. It should be something similar to:

```
cardano-cli conway governance drep registration-certificate
(--mainnet | --testnet-magic NATURAL)
( --drep-verification-key STRING
| --drep-verification-key-file FILE
| --drep-id STRING
)
[--metadata-url URL]
[--metadata-hash HASH]
--out-file FILE
```
** Note that we are using artifacts generated on #128,  #130 and #129 , so we may want to implement those first. 
 
## Why

From CIP1694

> DRep registration certificates include:
> 
> * a DRep ID
> * a deposit
> * an anchor
> 
> An **anchor** is a pair of:
> 
> * a URL to a JSON payload of metadata
> * a hash of the contents of the metadata URL
> 
> The structure and format of this metadata is deliberately left open in this CIP.
> The on-chain rules will not check either the URL or the hash.
> Client applications should, however, perform the usual sanity checks when fetching content from the provided URL.

## Personas

- [ ] Constitutional committee members
- [x] Delegate representatives
- [ ] SPOs
- [ ] dApp Devs
- [ ] Exchanges
- [ ] Wallets
- [ ] 3rd party tools
- [ ] ADA holders 

## Acceptance Criteria

1. The `cardano-cli conway governance drep registration-certificate` command should be available and functional.
2. The command should require either `--mainnet` or `--testnet-magic NATURAL` option to specify the target network for which the DRep registration certificate is generated.
3. The command should allow the user to provide the DRep verification key in one of the following ways:
- Using the --drep-verification-key STRING option to specify the DRep verification key directly as a string.
- Using the --drep-verification-key-file FILE option to specify the file containing the DRep verification key.
- Using the --drep-id STRING option to specify the DRep ID directly as a string.
4. If the `--metadata-url URL` option is provided, the command should include the URL to the JSON payload of metadata in the generated DRep registration certificate.
5. If the `--metadata-hash HASH` option is provided, the command should include the hash of the contents of the metadata URL in the generated DRep registration certificate.
6. The `--out-file FILE` option should be mandatory and used to specify the file where the generated DRep registration certificate will be saved.
7. The feature implementation should be well-documented, providing clear usage instructions for the cardano-cli conway governance drep registration-certificate command.
8. The command should handle errors gracefully and provide helpful error messages when required options are missing or invalid inputs are provided.
9. The feature should be thoroughly tested to ensure the correctness of the DRep registration certificate generation process.
10. The documentation should be updated to include the new feature, explaining its purpose and usage.

## Definition of Done (DoD)

- [ ] [Acceptance Criteria + User Stories & DoD](https://input-output.atlassian.net/wiki/spaces/QA/pages/3584229468/Acceptance+Criteria+DoD) created and singed-off (by PO, dev & test owners)
- [ ] Builds successfully on CI
- [ ] Code & Test review (as per Acceptance Criteria)
- [ ] There is documentation and/or examples for the new functionality (usage/response)
- [ ] Log/record changes on **Vnext** (or similar depending on what we adopt)
- [ ] Ticket number(s) included in PR description
- [ ] All Acceptance Criteria met and covered by dev/unit/property/integration tests
- [ ] System/E2E automated tests + System Test Engineer Owner Sign-off

# Sign-off

- [ ] Product Owner
- [ ] Dev Owner
- [ ] System Test Engineer Owner

> **_NOTE:_**  Ideally, we should merge only fully implemented and tested features into the master branch. 
> So all the above steps are required for the PR to be merged.  
> In order to avoid the PRs becoming stale and requiring to be rebased on master, these can be merged 
> after a reasonable time (current agreement is 3 days) if the System Test Engineer Owner's sign-off 
> was not provided (last step in the DoD).

> **_IMPORTANT:_** Any deviation from the plan should be discussed and agreed as a comment in the Feature file. 

## Related PRs

**Comment by Hornan7** [comment]
I'm not sure if its the right place for this, but would it be posible to add a "query stake distribution" for DReps
```
cardano-cli query stake-distribution
--socket path SOCKET PATH
[--shelley-mode
|--byron-mode [--epoch-slots SLOT]
|--cardano-mode [--epoch-slots SLOT]
]
(--stake-pool | --drep)
(--mainnet | --testnet-magic NATURAL)
[--out-file FILE]
```
I also made an issue about it #153 😄👍

**Comment by CarlosLopezDeLara** [comment]
@Hornan7 A new issue is better for new Feature requests, thanks for that #153
