### ISSUE TITLE
[BUG] - `transaction build` hangs indefinitely with 100% CPU load

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-cli#135]
## Description

For certain combination of arguments, the `cardano-cli transaction build` hangs indefinitely. The process utilizes a CPU core for 100%.

I was able to reproduce the hang eg. while registering new stake pool:

> cardano-cli transaction build --tx-in "f69e17bc8564f1450cde76c5c225ceaa8224267e8a3f8493461fb68ed2396852#0" --certificate-file pool_unqb_pool_reg.cert --change-address addr_test1qpsh9gwk7pa4r0f98adj3xuyx83u0h36rr70fwleckay8eae6m2rqzvc53w8nj2p8tpqf7mugyks2y42wwlj9fe2rspsdx8sfe --witness-override 3 --out-file test_create_stake_pool_ci0_jpj_unqb_1_True_reg_pool_tx.body --babbage-era --testnet-magic 42

There is nothing interesting in `strace` output.

I can reproduce the issue only with latest cardano-cli release 8.4.1.0. The issue is not present with the cardano-cli bersion that is bundled with cardano-node 8.2.0-pre (cardano-cli version 8.4.0.0).

**Comment by kevinhammond** [comment]
Thank you @mkoura

**Comment by carbolymer** [comment]
Caused by an infinite loop in this instance https://github.com/input-output-hk/cardano-api/blob/2d31baf34ac42f70eca199a832843039e61b2709/cardano-api/internal/Cardano/Api/Certificate.hs#L209

**Comment by mkoura** [comment]
Already fixed by https://github.com/input-output-hk/cardano-api/pull/170
