### ISSUE TITLE
[FR] - add Cardano-cli query stake-distribution (for DReps)

### ISSUE THREAD

**Issue by Hornan7** [input-output-hk/cardano-cli#153]
**Internal/External**
*External*   otherwise.

**Area**
*Other*   Cardano-cli command (sancho testnet)

**Describe the feature you'd like**
A command or an option to query DRep stake distribution.

**Describe alternatives you've considered**
```
cardano-cli query stake-distribution
--socket path SOCKET PATH
[--shelley-mode
|--byron-mode [--epoch-slots SLOT]
|--cardano-mode [--epoch-slots SLOT]
]
(--stake-pool | --drep)
(--mainnet | --testnet-magic NATURAL)
[--out-file FILE]
```

**Additional context / screenshots**
Right now on Sancho testnet there is no way for us to query the stake distribution of registered DReps. It would be usefull to know our actual "delegated voting power"

**Comment by CarlosLopezDeLara** [comment]
cardano-cli (main) now includes: 
 
`cardano-cli conway governance query drep-stake-distribution`

Feature to be included on next (pre) release.
