### ISSUE TITLE
[FEATURE] parameters for voter type and answer as single parameters

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-cli#154]
*External* 

**Area**
*Conway*

* ~Please also add the governance actions/vote/etc. commands to the cardano-cli `build-raw` command~

* Wouldn't it be better to have a single parameter for the answer and one for the keytype instead of flags for everything?
   Like: 
   ```
   --answer abstain | yes | no
   --type ccm | drep | spo
   --verification-key-file xxx
                            Filepath of the stake pool verification key, drep verification key, constitutional committee member verification key
   --verification-key-string xxx
                            Stake pool verification key, drep verification key, constitutional committee member verification key
   ```
   And not --yes --no --abstain --spo --drep --constitutional-committee-member. I think that would make it more future proof and not such a mess with the flags?
   Also, the input parameters will/should change accordingly to the voter type. In case of a drep, shouldn't it than be the derived drep vkey and not the stakepool vkey/string anymore?

Thanks!

Best regards, Martin

**Comment by CarlosLopezDeLara** [comment]
I'm going to edit the title so that it refers only to the second FR.  There is an existing Issue about build-raw tracked here https://github.com/input-output-hk/cardano-cli/issues/12

**Comment by CarlosLopezDeLara** [comment]
Vote typre is now automatically detected from the key type. Will revisit the topic about --yes --no --abstain on a later review bu t I think the critical part was what has been already done.
