### ISSUE TITLE
[BUG] - Cannot deregister stake address

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-cli#157]
## Description

On cardano-node 8.2.1-pre (with cardano-cli 8.5.0.0), in Babbage era, an attempt to deregister stake address fails with `StakeKeyAlreadyRegisteredDELEG`

## Steps to Reproduce

> cardano-cli stake-address deregistration-certificate --stake-verification-key-file test_addr_registration_deregistration_ci0_tgc_pool_user_addr0_stake.vkey --out-file test_addr_registration_deregistration_ci0_obh_True_addr0_stake_dereg.cert

> cardano-cli transaction build --tx-in "ee9ce89ad066cefe7379d1789f1b81615d5d3a97720a6e1594d821dd24424bf5#0" --certificate-file test_addr_registration_deregistration_ci0_obh_True_addr0_stake_dereg.cert --change-address addr_test1qph9nkyzscvsvcu2kff7hypfejdwqqtswqvzgmuz8rxqfytnvmxlvcx439g4skg9n98aqv9u574kc3fld2e80e7m0ggszadut5 --witness-override 2 --out-file test_addr_registration_deregistration_ci0_obh_True_dereg_tx.body --babbage-era --testnet-magic 42

> ardano-cli transaction sign --tx-body-file test_addr_registration_deregistration_ci0_obh_True_dereg_tx.body --testnet-magic 42 --signing-key-file test_delegation_pool_user_ci0_addr0.skey --signing-key-file test_addr_registration_deregistration_ci0_tgc_pool_user_addr0_stake.skey --out-file test_addr_registration_deregistration_ci0_obh_True_dereg_tx.signed

> cardano-cli transaction submit --testnet-magic 42 --tx-file test_addr_registration_deregistration_ci0_obh_True_dereg_tx.signed --cardano-mode

> Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [DelegsFailure (DelplFailure (DelegFailure (StakeKeyAlreadyRegisteredDELEG (KeyHashObj (KeyHash "bd59de559eeed4684270acc3c0ca84ab4af9f40dbd238f03b7cd53be")))))])

## Additional Context

It can be reproduced on current cardano-node master as well (`56720a9526c3c7299c89d49694cd621f158b7aca`).

**Comment by carbolymer** [comment]
appears that during `transaction build` ledger deserializes deregistration certificate as registration certificate
```
$ cat deregistration.cert                                             
{
    "type": "CertificateShelley",
    "description": "Stake Address Deregistration Certificate",
    "cborHex": "82008200581c9e9196aa690631f1d7d348b3ee0489da0383a1afefecb0d945186d02"
}

$ cardano-cli text-view decode-cbor --in-file ./deregistration.cert
82  # list(2)
   00  # int(0)
   82  # list(2)
      00  # int(0)
      58 1c 9e 91 96 aa 69 06 31 f1 d7 d3 48 b3 ee 04 
      89 da 03 83 a1 af ef ec b0 d9 45 18 6d 02  # bytes(28)

$ cardano-cli transaction build \
  --tx-in $($cli query utxo --address $(cat payment.addr) --out-file  /dev/stdout | jq -r 'keys[0]') \
  --certificate-file deregistration.cert \
  --change-address $(cat payment.addr) \
  --witness-override 2 \
  --out-file test_addr_registration_deregistration_ci0_obh_True_dereg_tx.body \
  --babbage-era
TxCertificates CertificatesInBabbageEra
    [ ShelleyRelatedCertificate ShelleyToBabbageEraBabbage
        ( ShelleyTxCertDelegCert
            ( ShelleyRegCert
                ( KeyHashObj
                    ( KeyHash "9e9196aa690631f1d7d348b3ee0489da0383a1afefecb0d945186d02" )
                )
            )
        )
    ]
    ( BuildTxWith
        ( fromList [] )
    )
Estimated transaction fee: Lovelace 171265
````
