### ISSUE TITLE
in conway era query ledger-state returns cbor instead of json

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#200]
ledger-state json output is broken in conway. Since we don't have dbsync and we dont have custom queries for governance actions and votes, querying the ledger state in json is a very useful tool for testing and debugging.

**Comment by kderme** [comment]
> Since we don't have dbsync

Just an fyi, there is a [db-sync version](https://github.com/input-output-hk/cardano-db-sync/releases/tag/sancho-1-0-0), with support for Conway (gov actions, votes, dreps, certificates etc). Still a very useful task though.
