### ISSUE TITLE
Work around optparse-applicative limitations for parsing complex command lines

### ISSUE THREAD

**Issue by newhoggy** [input-output-hk/cardano-cli#205]

**Comment by newhoggy** [comment]
We are unable to define parsers of arbitrarily complex types and fallback between them due to limitations of the `optparse-applicative` library.

We need either need a more permanent solution or a viable work around.

There is a discussion here.

https://input-output-rnd.slack.com/archives/C057E9CJTPH/p1692887691962709?thread_ts=1692850710.826029&cid=C057E9CJTPH

**Comment by CarlosLopezDeLara** [comment]
@newhoggy is this completed?
