### ISSUE TITLE
Update description fields on Delegation certificates

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#221]
This is a JSON of a DREP delegation certificate, it is exactly the same description as in a Stake pool delegation certificate.

```
{
    "type": "CertificateShelley",
    "description": "Stake Address Delegation Certificate",
    "cborHex": "83098200581cc827e7d1fb57cf12662203612fe1f0bb3578574b16f90f4a78cd355c8200581c44924d8233e23a4eda97ba2ce0a336d6152171e70960396b4903eb8a"
}
```
Let's change the description on the different types of certificates: 

“Stake Delegation Certificate” <-- For stake pool delegation certificates
“Vote Delegation Certificate” <-- For Drep delegation certificates
“Stake and Vote Delegation Certificate” <— for that interesting case where you can have a single cert with both delegations

**Comment by Ryun1** [comment]
I propose to use the naming of:
- VOTE delegation certificate

To match the[ ledger design](https://github.com/input-output-hk/cardano-ledger/blob/master/eras/conway/test-suite/cddl-files/conway.cddl#L303)

**Comment by CarlosLopezDeLara** [comment]
I like the idea, it shows the purpose of the certificate more clearly, We might need to update both so that is 

stake delegation certificate
vote delegation certificate
