### ISSUE TITLE
"internal query mismatch" with `transaction build` and de-registration cert

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-cli#268]
## Description

In Babbage era, when building a tx for de-registering stake address using `transaction build`, I get a `fromConsensusQueryResult: internal query mismatch` error.

## Steps to Reproduce

1. Try to build the tx

> cardano-cli transaction build --tx-in "c56a7e203f6872444096a9cf2a85accd204d2aa1f753b355f549801b69c6724c#0" --certificate-file test_deregister_registered_ci0_evb_True_addr0_stake_dereg.cert --change-address addr_test1qpflhv3yq5y9he6lqmkplyyzf589u2xtyppza8m9qf25uhzauzsfq4mzcq3k40pdl2gzx4pqqg9jnpcvqexe54temsjq8lp5ut --witness-override 2 --out-file test_deregister_registered_ci0_evb_True_dereg_tx.body --babbage-era --testnet-magic 42

2. See the error

> cardano-cli: fromConsensusQueryResult: internal query mismatch
     CallStack (from HasCallStack):
     error, called at internal/Cardano/Api/Query.hs:994:5 in cardano-api-8.16.3.0-G7kRzKW9kJv6Ljv11qXs3W-internal:Cardano.Api.Query

## Additional Context

OS: Fedora 37
cardano-cli: 8.6.1.0 (part of current node master 4139153d4510f3671a67f3dcdf274d3caac52a06)

Dereg cert:
[test_deregister_registered_ci0_evb_True_addr0_stake_dereg.zip](https://github.com/input-output-hk/cardano-cli/files/12576928/test_deregister_registered_ci0_evb_True_addr0_stake_dereg.zip)

**Comment by smelc** [comment]
@carbolymer> was this one fixed by https://github.com/input-output-hk/cardano-api/pull/239?

**Comment by carbolymer** [comment]
I think so. @mkoura can this issue be closed?

**Comment by mkoura** [comment]
Already fixed.
