### ISSUE TITLE
build-raw is not working for submitting actions and votes

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#290]
```
cardano-cli --version
cardano-cli 8.8.0.0 - linux-x86_64 - ghc-9.2
git rev 20b7b2b1e81cbb580736c93062be85485ac98ded
```

The command `cardano-cli conway transaction build-raw` is not working with actions or votes. It is missing `--vote-file`and `proposal-file`

**Comment by CarlosLopezDeLara** [comment]
closing as it is not yet on the priorities and we have a feature request ticket for this https://github.com/input-output-hk/cardano-cli/issues/12

**Comment by gitmachtl** [comment]
@CarlosLopezDeLara please reopen, we still need those updates

**Comment by CarlosLopezDeLara** [comment]
@gitmachtl It was a duplicate of #12 We are still tracking this. FYI we are close to start working on `build-raw` there are just a few things ahead in the line.

**Comment by gitmachtl** [comment]
thx @CarlosLopezDeLara
