### ISSUE TITLE
[BUG] - transaction submission fails in conway era

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-cli#31]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
Transaction submission fails

**Steps to reproduce**
1. Fork to conway era
2. Build and sign a transaction moving funds
3. submit transaction

Get error:
```
nix run .#cardano-cli -- transaction submit --testnet-magic 42 --tx-file ../cardano-world/tx-foo.txsigned
trace: WARNING: 9.2.7 is out of date, consider using 9.2.8.
trace: WARNING: 9.2.7 is out of date, consider using 9.2.8.
trace: WARNING: 9.2.7 is out of date, consider using 9.2.8.
MuxError MuxBearerClosed "<socket: 11> closed when reading data, waiting on next header True"

cardano-cli: MuxBearerClosed "<socket: 11> closed when reading data, waiting on next header True"
```

**Expected behavior**
Transaction added to mempool and broadcasted

**System info (please complete the following information):**
- OS Name: [e.g. Ubuntu]
- OS Version [e.g. 20.04]

If the git revision is reported to be `0000000000000000000000000000000000000000`, please use `cabal build` instead of `cabal install` to build the binaries because `cabal install` does not record the git revision in the binaries.

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by dnadales** [comment]
By enabling `TraceLocalConnectionManager` we were able to see the error that caused the CLI and node to disconnect:

```
[pampero:cardano.node.LocalTxSubmissionServer:Info:1285] [2023-06-21 09:20:06.87 UTC] fromList [("kind",String "TraceLocalTxSubmissionServerEvent")]
[pampero:cardano.node.LocalConnectionManager:Info:1282] [2023-06-21 09:20:06.87 UTC] TrConnectionHandler (ConnectionId {localAddress = LocalAddress "node.socket", remoteAddress = LocalAddress "node.socket@0"}) (TrConnectionHandlerError InboundError Prelude.undefined
CallStack (from HasCallStack):
  error, called at libraries/base/GHC/Err.hs:79:14 in base:GHC.Err
  undefined, called at src/Cardano/Ledger/Conway/TxBody.hs:311:18 in cardano-ledger-conway-1.2.0.0-7UYvZX52Pe46ZQ74ZCYNdX:Cardano.Ledger.Conway.TxBody ShutdownPeer)
[pampero:cardano.node.LocalConnectionManager:Debug:1282] [2023-06-21 09:20:06.87 UTC] TrConnectionCleanup (ConnectionId {localAddress = LocalAddress "node.socket", remoteAddress = LocalAddress "node.socket@0"})
```

The function `certsTxBodyG` used to validate transactions was undefined. This function has been recently [removed](https://github.com/input-output-hk/cardano-ledger/pull/3387/files#diff-7e07425974e4e6ee031dd22df474b0c66ee9ea04e4a0b107757f289002d8c85bL310-L311).

**Comment by newhoggy** [comment]
There is an integration test for transactions in Conway in this PR: https://github.com/input-output-hk/cardano-node/pull/5366

Once this fixed in `cardano-node`, the PR can be rebased onto that the fix to confirm the feature works.
