### ISSUE TITLE
[BUG] - query utxo --whole-utxo fails

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-cli#32]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
Error when fetching whole utxo

**Steps to reproduce**
1. Fork to conway
2. Run
```
nix run -L .#cardano-cli -- query utxo --whole-utxo --testnet-magic 42
trace: WARNING: 9.2.7 is out of date, consider using 9.2.8.
trace: WARNING: 9.2.7 is out of date, consider using 9.2.8.
trace: WARNING: 9.2.7 is out of date, consider using 9.2.8.

cardano-cli: DecoderFailure (LocalStateQuery HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AllegraEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (MaryEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AlonzoEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (BabbageEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (ConwayEra StandardCrypto)) ('[] *)))))))) Query (BlockQuery (HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AllegraEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (MaryEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AlonzoEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (BabbageEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (ConwayEra StandardCrypto)) ('[] *))))))))))) ServerAgency TokQuerying BlockQuery (QueryIfCurrent (QS (QS (QS (QS (QS (QS (QZ GetUTxOWhole))))))))) (DeserialiseFailure 493 "Expected a positive Coin. Got 0 (zero).")
```

**Expected behavior**
output entire utxo set.

**System info (please complete the following information):**
- OS Name: [e.g. Ubuntu]
- OS Version [e.g. 20.04]

If the git revision is reported to be `0000000000000000000000000000000000000000`, please use `cabal build` instead of `cabal install` to build the binaries because `cabal install` does not record the git revision in the binaries.

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by Jimbo4350** [comment]
`"Expected a positive Coin. Got 0 (zero)."` appears to be coming from https://github.com/input-output-hk/cardano-ledger/blob/218c3965945e5209100a06dd96e48332e813e1c2/libs/cardano-ledger-core/src/Cardano/Ledger/Coin.hs#L151

**Comment by lehins** [comment]
This can be closed since it was fixed in ledger with https://github.com/input-output-hk/cardano-ledger/pull/3600
