### ISSUE TITLE
No love for extended (dRep) verification keys

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-cli#352]
Version Info:
```
cardano-cli 8.12.0.0 - linux-x86_64 - ghc-8.10
git rev f1ce770834bf7150ca29cb647065c9e62d39be1a
```

test.drep.vkey:
```json
{
  "type": "DRepExtendedVerificationKey_ed25519_bip32",
  "description": "Delegate Representative Verification Key",
  "cborHex": "5840b0cd9e6e3e274f4f38f55ef274af123cf4600ac0c58294399b7e076175262553dde8b75f847f2b7e61a8748627292a06d739c8ba8e78ac83e666030d1093fb3e"
}
```

```console
cardano-cli conway governance query drep-state --testnet-magic 4 --drep-verification-key-file test.drep.vkey

Command failed: governance query drep-state  Error: Error reading delegation representative key: test.drep.vkey: TextEnvelope type error:  Expected: DRepVerificationKey_ed25519 Actual: DRepExtendedVerificationKey_ed25519_bip32
```

I am seeing a general lack in support of extended verification keys with cardano-cli. Is this not supported on purpose also for other commands? If so, i am good, but  it should be stated somewhere. Some test in the past showed that extended signing keys are working normally.

**Comment by gitmachtl** [comment]
Also its not possible to convert a dRep extended vkey to a non-extended one:

```console
cardano-cli conway key non-extended-key --extended-verification-key-file test.drep.vkey --verification-key-file /dev/stdout

Command failed: key non-extended-key  Error: Invalid key.
```

@CarlosLopezDeLara so being able to directly use extended vkeys in all commands might be a feature, but the conversion should work. so i would say thats a bug?

**Comment by CarlosLopezDeLara** [comment]
@gitmachtl  Its only a bug if the feature has been implemented and it doesn't work as expected. I'm creating https://github.com/input-output-hk/cardano-cli/issues/358 to track it separately.

**Comment by gitmachtl** [comment]
@CarlosLopezDeLara @disassembler suggested to open up another issue for general extended verification key support and cardano-cli.

**Comment by CarlosLopezDeLara** [comment]
@gitmachtl Yes indeed, I'm leaving this one open as a reminder till I create a more general issue.
