### ISSUE TITLE
[FEATUE] A query for the stake key deposited amount | Stake-Address-Info is not showing the deposited amount

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-cli#353]
Version Info:
```
cardano-cli 8.12.0.0 - linux-x86_64 - ghc-8.10
git rev f1ce770834bf7150ca29cb647065c9e62d39be1a
```
**PROBLEM STATEMENT:** 

With the new stake address registration certificate type7 in conway era, we can now set a deposit amount. That exact deposit amount should also be used to generate the de-registration/retire certificate. For that we would need a method to query the registered amount. Best place imo would be within the stake-address-info query.

Currently we get something like:
```json
[
  {
    "address": "stake_test1urqntq4wexjylnrdnp97qq79qkxxvrsa9lcnwr7ckjd6w0cr04y4p",
    "delegation": "pool1rkfs9glmfva3jd0q9vnlqvuhnrflpzj4l07u6sayfx5k7d788us",
    "rewardAccountBalance": 297059772555
  }
]
```

So adding a new entry `deposited` would be a good solution imo to query the correct value before generating the de-registration/retire certificate.

P.S.: Same goes for the dRep information query. That should also list the deposited amount if possible.

**Comment by CarlosLopezDeLara** [comment]
Analyze if the proposed is a feasible solution.

**Comment by carlhammann** [comment]
For DReps, doesn't `cardano-cli conway query drep-stake-distribution` solve this?

**Comment by CarlosLopezDeLara** [comment]
No, I don't think so @carlhammann,  because that does not show the deposited amount either

```
cardano-cli conway governance query drep-stake-distribution --testnet-magic 42 --drep-verification-key-file example/dreps/drep1.vkey
[
    [
        {
            "contents": "1432d2954dc39e49ed15d48fa95bfd4ef7b79dbaa9c52f0b4b4cc457",
            "tag": "DRepKeyHash"
        },
        589986540336
    ]
```
]

**Comment by carlhammann** [comment]
My bad, @CarlosLopezDeLara. I think `cardano-cli conway query drep-state` [should show](https://github.com/input-output-hk/cardano-cli/blob/b83c58d340c9fa0a0952749ac3f718b8422bf3ee/cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs#L1475) the deposit (for DReps).

**Comment by gitmachtl** [comment]
@CarlosLopezDeLara @carlhammann 
will the new query output show an amount of 2000000 lovelaces for pre conway stake key registrations? If not, from what source should we query the right data in case of a de-registration?

**Comment by carlhammann** [comment]
@gitmachtl Drilling down, the command `cardano-cli query stake-address-info` ends up calling [`lookupDepositDState`](https://github.com/input-output-hk/cardano-ledger/blob/c6177454244e7c4aa07a0af9c88e96d774608306/libs/cardano-ledger-core/src/Cardano/Ledger/CertState.hs#L218), which is [also used](https://github.com/input-output-hk/cardano-ledger/blob/c6177454244e7c4aa07a0af9c88e96d774608306/eras/shelley/impl/src/Cardano/Ledger/Shelley/LedgerState/RefundsAndDeposits.hs#L97) to calculate the refunds at deregistration. So, I think the amount should be the correct one for de-registrations.

**Comment by carlhammann** [comment]
@gitmachtl See also this: https://github.com/input-output-hk/cardano-cli/issues/417

**Comment by carlhammann** [comment]
@gitmachtl My comment from three weeks ago is wrong. I had a few interactions with the ledger team that cleared up some of my misunderstandings; there are separate places for remembering the different types of deposits. The current command should return the staking deposit that was paid by the key. There's currently no command in the CLI that will return _all_ deposits associated with a key, and I'm investigating how we might implement that.

**Comment by gitmachtl** [comment]
@carlhammann (EDIT: i read your comment wrong)

ok, so it would be really good to have a query - preferable in the stake-address-info query - to see all currently deposited values. in case of a deregistration i guess we have to sum up all of these to generate the correct transaction balance. or can a stake key not be retired if there is still an action deposit on it? or would it simply retire and all the associated things with that key would be cleared out of the ledger-state?

**Comment by gitmachtl** [comment]
unstale
