### ISSUE TITLE
stake-address-info -  delegationDeposit

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#417]
The value reported under "delegationDeposit", in reality, not only covers delegation deposits, but also governance action deposits that are not returned yet. 

If it is not possible to separate those deposits into different fields, it would be better to rename `delegationDeposit` into `deposits`

```
cardano-cli conway query stake-address-info --address $(cat example/utxo-keys/stake4.addr) --testnet-magic 42

[
    {
        "address": "stake_test1urdx7k79ch3mdvjgt6h3vxtsnml9vjtm72gfs0z2qcq4xds8srrre",
        "delegation": null,
        "delegationDeposit": 1000000000,
        "rewardAccountBalance": 2422086304
    }
]%
```

**Comment by gitmachtl** [comment]
@CarlosLopezDeLara 
i need clarification on this for the tool integration. would be good to have all informations about a stake-address/stake-key in the stake-address-info query. not in different places. so in case of an open action deposit, what would happen if the stake-key is retired? will all the action stuff be cleared out from the ledger-state or is it all blocked and you can only retire a stake-key once there is no other deposit open other than the address registration deposit?

**Comment by gitmachtl** [comment]
keepalive
