### ISSUE TITLE
cardano-cli conway governance action create-constitution: rework hash arguments

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#420]
Remove the metadata word from 

```
--constitution-anchor-url TEXT
( --constitution-anchor-metadata TEXT
| --constitution-anchor-metadata-file FILE
| --constitution-anchor-metadata-hash HASH
)
```

it should be

```
--constitution-anchor-url TEXT
( --constitution-anchor-text TEXT
| --constitution-anchor-file FILE
| --constitution-anchor-hash HASH
)
```

---

**[edit]**

Update from a [discussion on Slack](https://input-output-rnd.slack.com/archives/C031GFLC3DF/p1699022279259479):

* We will have `--constitution-anchor-url TEXT --constitution-anchor-hash HASH`, 
* and a command `cardano-cli conway governance hash --file --text` to create the `HASH`

**Comment by carlhammann** [comment]
@CarlosLopezDeLara, @smelc I'm all for making the flags shorter, but the proposed renaming loses clarity: the `file` and `hash` _do not include_ the anchor URL. (An anchor is an URL plus a hash of the contents behind that URL. The `text`, `file`, or `hash` are the options for a "hash source".)

**Comment by smelc** [comment]
As of dbbc5701e5f90a8e9218c134d6e78fbc6b24b747, commands affected by this change are:

* `create-constitution` (`--proposal-anchor-metadata`, `--proposal-anchor-metadata-file`, `--constitution-anchor-metadata`, `--constitution-anchor-metadata-file`)
* `update-committee` (`--proposal-anchor-metadata`, `--proposal-anchor-metadata-file`)
* `create-info` (same as previous)
* `create-no-confidence` (same as previous)
* `create-protocol-parameters-update` (same as previous)
* `create-treasury-withdrawal` (same as previous)
* `conway governance vote create` (`--vote-anchor-metadata`, `--vote-anchor-metadata-hash`)

**Comment by smelc** [comment]
I'm nearly done with this ([PR 442](https://github.com/input-output-hk/cardano-cli/pull/442)). In the end I propose we have three modes in the `conway governance hash` command, [like b2sum](https://man7.org/linux/man-pages/man1/b2sum.1.html):

* `--text` which takes the text to hash directly
* `--text-file` which takes a file and treats it as text, and hashes its content
* `--binary-file` which takes a treats it as binary, allowing PDF files, compressed files, etc; and hashes its content.

If we go with only `--text` and `--file`, we don't clearly state how we treat files, and will end up with unhappy users. Test-wise, those flags will allow us to be platform-agnostic and avoid failures on Windows.

**Comment by Jimbo4350** [comment]
https://github.com/input-output-hk/cardano-cli/pull/442#pullrequestreview-1722472440

**Comment by smelc** [comment]
I went for `--text`, `--file-text`, and `--file-binary` in the end, as it looked more consistent with existing flags, that tend to differentiate different behaviors by the suffix of the flag, rather than the start of the flag.

**Comment by smelc** [comment]
@CarlosLopezDeLara> another side effect of the PR is that I harmonized the flags of anchors of `vote create` with all the other commands:

* `--vote-anchor-url` becomes `--anchor-url`
* `--vote-anchor-metadata-hash` becomes `--anchor-data-hash`
