### ISSUE TITLE
Allow submitting transactions older than current node era

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-cli#439]
URGENT - With the node-release 8.6.0-pre an update was introduced:
`Do not allow submitting transactions older than current node era`

**This breaks hardware wallet support immediately, it breaks dApps it most likely also breaks cexes.**

There must be a way to at least submit `babbage-era` formatted transactions and certificates also in `conway-era`
to have a smooth transition between them. We need this for the tools/scripts/libs to catch up to the latest standard. 

> I can see that the CDDL has changed for transaction and how certain old certificates have also been changed. But it is required to have a default values set for older certs in the new era for older tx format. If not, maybe its possible to have an intermediate HF (which supports both formats but same functionality as current version) just to force everyone to upgrade to new tx format and then goes the actually HF with new format functionality
@ashisherc

@disassembler @CarlosLopezDeLara

**Comment by gabrielKerekes** [comment]
IMO the release note probably relates just to `cardano-cli`. More info regarding the release note would definitely be appreciated though as it's not really clear what it exactly means and it's confusing.

AFAIK there are no breaking changes in the CDDL which would affect HW wallets in Conway, except for the newly introduced fields and certs of course, but the txs should be backwards compatible still. The only breaking change should be in the certificates requiring a tag ([CDDL](https://github.com/input-output-hk/cardano-ledger/blob/master/eras/conway/impl/cddl-files/conway.cddl#L92) and [nonempty_oset<a> defintion](https://github.com/input-output-hk/cardano-ledger/blob/45f8572eee675e330a48f94c44ff78358d85be77/eras/conway/impl/cddl-files/mock/extras.cddl#L6)) but from what we've heard the tag shouldn't be mandatory in Conway 🤷

**Comment by gitmachtl** [comment]
> IMO the release note probably relates just to `cardano-cli`. More info regarding the release note would definitely be appreciated though as it's not really clear what it exactly means and it's confusing.

transactions signed on the cli with hw-wallets are transmitted via cardano-cli. so it is an issue.

**Comment by KubqoA** [comment]
> > IMO the release note probably relates just to `cardano-cli`. More info regarding the release note would definitely be appreciated though as it's not really clear what it exactly means and it's confusing.
> 
> transactions signed on the cli with hw-wallets are transmitted via cardano-cli. so it is an issue.

I believe it shouldn't be, you can still use the previous version of `cardano-cli` to submit the transaction until you can update all the tooling, the schema should be backwards compatible. So until tooling is updated I think you should be able to in theory still run the older node and older cardano-cli an get your transactions through. Correct me if I am wrong.

**Comment by gitmachtl** [comment]
> > > IMO the release note probably relates just to `cardano-cli`. More info regarding the release note would definitely be appreciated though as it's not really clear what it exactly means and it's confusing.
> > 
> > 
> > transactions signed on the cli with hw-wallets are transmitted via cardano-cli. so it is an issue.
> 
> I believe it shouldn't be, you can still use the previous version of `cardano-cli` to submit the transaction until you can update all the tooling, the schema should be backwards compatible. So until tooling is updated I think you should be able to in theory still run the older node and older cardano-cli an get your transactions through. Correct me if I am wrong.

This is not a workable upgrade path. I am a tool provider, i have to test all things over and over again with different Eras and Hardforks. Cutting off Hardware Wallet Support is not an option. We will have several other releases until we are in an endphase with the node and cardano-cli. Parameters/Flags are changing from version to version nowadays. There is simply no way that we will go live on mainnet or preprod by running the lastest node and using a months old cli version in the hope it will work.

**Comment by rdlrt** [comment]
+1 - just want to mention, would be the same for CNTools as well

**Comment by AndrewWestberg** [comment]
This will break Jormanager. This also will break any dapp using cardano-cli to submit their transactions.

**Comment by gitmachtl** [comment]
Also, all Babbage-Era Certificates must be supported in Conway-Era too. And afaik the plan is to only remove the older certificates after Conway-Era. So it must be possible to do the usual StakeKey(De)Registration,StakePool(De)Registration,Delegation,etc. all with Babbage-Era Certificates. Otherwise it would again break f.e. HW-Wallets until we have a native Conway-Era support fully rolled out for those too. But as you know from the past, this takes a while.

**Comment by CarlosLopezDeLara** [comment]
Gentlemen, apologies for the heart attack caused.  The message on the release notes should have said:  

_"Transaction **build** command does not allow constructing transactions in eras differing to the node being queried"_

That means that the change is not as dramatic as it looks like. We can still use `build-raw` to build transactions formatted for an older era i.e. Babbage (even Alonzo); those transactions of course can still be witnessed and submitted with no issue.  For example this tx in SanchoNet

```
➜  keys cardano-cli alonzo transaction build-raw \
--tx-in 04cc7db698618c050383a1dfaa27295ed6aa6db40ac9663615da1d52e308f8b9#0 \
--tx-out $(cat payment.addr)+9998000000 \
--fee 0 \
--out-file tx.raw
➜  keys cardano-cli conway transaction calculate-min-fee \
--tx-body-file tx.raw \
--testnet-magic 4 \
--protocol-params-file pparams.json \
--tx-in-count 1 \
--tx-out-count 1 \
--witness-count 1
171265 Lovelace
➜  keys cardano-cli alonzo transaction build-raw \
--tx-in 04cc7db698618c050383a1dfaa27295ed6aa6db40ac9663615da1d52e308f8b9#0 \
--tx-out $(cat payment.addr)+9998657470 \
--fee 171265 \
--protocol-params-file pparams.json \
--out-file tx.raw
➜  keys cardano-cli alonzo transaction witness \
--tx-body-file tx.raw \
--signing-key-file payment.skey \
--testnet-magic 4 \
--out-file payment.witness
➜  keys cardano-cli alonzo transaction assemble \
--tx-body-file tx.raw \
--witness-file payment.witness \
--out-file tx.signed
➜  keys cardano-cli alonzo transaction submit \
--testnet-magic 4 \
--tx-file tx.signed
Transaction successfully submitted.
```

The change **only** affects `build`; for example: 

```
➜  keys cardano-cli alonzo transaction build --testnet-magic 4 \
--tx-in 04cc7db698618c050383a1dfaa27295ed6aa6db40ac9663615da1d52e308f8b9#0 \
--change-address $(cat payment.addr) \
--out-file tx.raw
Command failed: transaction build  Error: Transactions can only be produced in the same era as the node. Requested era: Conway, node era: Alonzo.
```

**Comment by gitmachtl** [comment]
Ok thank you @CarlosLopezDeLara for the clarification. I can live with that, because i only use `build-raw` and not the simpler `build` command. And, Babbage-Era-Certificates are also still working in Conway-Era right? I mean they work right now, so i don't assume that the support will be removed until after Conway?

**Comment by CarlosLopezDeLara** [comment]
@gitmachtl Yes, Babbage certificates should work just fine as well with `build-raw` in Conway. Of course, please let me know if you encounter any issues while working with certs.

**Comment by gitmachtl** [comment]
Thx, i think i can close this issue than. As `build-raw` is not affected by this change, we should be fine.
