### ISSUE TITLE
Align create-constitution flags with --anchor-(url|data-hash) new behavior

### ISSUE THREAD

**Issue by smelc** [input-output-hk/cardano-cli#447]
# Context 

This is a follow-up of https://github.com/input-output-hk/cardano-cli/issues/420

# Goal

`cardano-cli conway governance action create-constitution` has the following flags:

```
  --constitution-anchor-url TEXT
                           Constitution anchor URL.
  --constitution-anchor-metadata TEXT
                           Constitution anchor contents as UTF-8 encoded text.
  --constitution-anchor-metadata-file FILE
                           Constitution anchor contents as a text file.
  --constitution-anchor-metadata-hash HASH
```

To be consistent with https://github.com/input-output-hk/cardano-cli/issues/420, we want to:

* Delete `--constitution-anchor-metadata`
* Delete `--constitution-anchor-metadata-file`
* **[edited]** Rename `--constitution-anchor-url` to `--constitution-url`
* **[edited]** Rename `--constitution-anchor-metadata-hash` to `--constitution-hash`

**Comment by smelc** [comment]
cc @CarlosLopezDeLara

**Comment by CarlosLopezDeLara** [comment]
@smelc 

I think for proposals its correct, but for constitution we can sinplify to 

--constitution-url 
--constitution-hash

**Comment by smelc** [comment]
@CarlosLopezDeLara> makes sense, I updated the issue's description accordingly! Thanks :heart:
