### ISSUE TITLE
StakeAddress Registration deposit value not optional for conway era

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-cli#449]
The current syntax description of cardano-cli 8.13.0.0 shows

```
cardano-cli conway stake-address registration-certificate
Usage: cardano-cli conway stake-address registration-certificate
                                                                   ( --stake-verification-key STRING
                                                                   | --stake-verification-key-file FILE
                                                                   | --stake-script-file FILE
                                                                   | --stake-address ADDRESS
                                                                   )
                                                                   [--key-reg-deposit-amt NATURAL]
                                                                   --out-file FILE
```

Performing such a stake-address registration-certificate generation action without the `--key-reg-deposit-amt` value set results in the error:
```
Command failed: stake-address registration-certificate  Error: Stake address deposit required.
```

So this deposit amount value - starting with conway era - is actually not an optional value, its a required one right?

**Comment by smelc** [comment]
It's end of Friday.. so to take with a grain of salt, but indeed something looks off. This error seems to happen in this case ([here](https://github.com/input-output-hk/cardano-cli/blob/8bde151b94813e687071435df0c1653c64b7dfef/cardano-cli/src/Cardano/CLI/EraBased/Run/StakeAddress.hs#L166)) which is flagged impossible according to the comment:

```hs
    ShelleyBasedEraConway ->
      case mdeposit of
        -- TODO: This error constructor will never be called
        Nothing -> Left StakeAddressRegistrationDepositRequired
        Just dep ->
          return $ StakeAddrRegistrationConway ConwayEraOnwardsConway dep stakeCred
```

My guess is that you're right @gitmachtl and indeed the parser is not restrictive enough. I'll investigate.
