### ISSUE TITLE
[FR] - Human readable genesis.json file

### ISSUE THREAD

**Issue by iccicci** [input-output-hk/cardano-cli#461]
**Internal/External**
*Internal* Lace back-end

**Area**
*Other* `genesis.json` file generated by `cardano-cli genesis create-staked`.

**Describe the feature you'd like**
In v8.6.0, the said command generates a _compact_ version of the file.
Since all other generated _json_ files are in a _human readable_ format, I suggest to change the format for this file.

Example
I suggest to make it as
```
{
  "systemStart": "2023-11-16T17:38:18.997531994Z",
  "networkMagic": 888,
  ...
```
rather than
```
{"systemStart":"2023-11-16T17:38:18.997531994Z","networkMagic":888,...
```

**Describe alternatives you've considered**
I'm fine: a simple `cat genesis.json | jq > genesis.new.json` solves my problem.

**Comment by smelc** [comment]
Maybe for you @carlhammann? You modified `create-stacked` recently right?

**Comment by carlhammann** [comment]
@smelc Since we now [split work differently](https://github.com/input-output-hk/cardano-cli/issues/473#issuecomment-1822939232), maybe you'll want to do this, after all? :smile:

**Comment by smelc** [comment]
@carlhammann> sounds good :+1:
