### ISSUE TITLE
cli 8.13.0.0 generates "ShelleyCertificates" for StakeAddress(De)Registration in conway era

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-cli#465]
```console
$ cardano-cli version
cardano-cli 8.13.0.0 - linux-x86_64 - ghc-8.10
git rev 735e6c97740c8def5d6e462bf5a29cbe6d323cfe
```
**EDIT: The type should be CertificateConway** 

```console
$ cardano-cli conway stake-address registration-certificate --stake-address stake_test1uqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqdd4srp --key-reg-deposit-amt 2000000 --out-file /dev/stdout
```
```json
{
    "type": "CertificateShelley",
    "description": "Stake Address Registration Certificate",
    "cborHex": "83078200581c000000000000000000000000000000000000000000000000000000001a001e8480"
}
```

The `type` should be `CertificateConway` i guess?

Same goes for the deregistration(retirement) certificate
```console
$ cardano-cli conway stake-address deregistration-certificate --stake-address stake_test1uqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqdd4srp --key-reg-deposit-amt 2000000 --out-file /dev/stdout
```
```json
{
    "type": "CertificateShelley",
    "description": "Stake Address Deregistration Certificate",
    "cborHex": "83088200581c000000000000000000000000000000000000000000000000000000001a001e8480"
}
```

Currently the cli is handling it fine using those certificates in transactions in conway era.

**Comment by smelc** [comment]
@CarlosLopezDeLara> what do you think?

**Comment by smelc** [comment]
From @CarlosLopezDeLara on Slack ([message](https://input-output-rnd.slack.com/archives/C031GFLC3DF/p1700578873567269)):

> Indeed, `cardano-cli conway stake-address deregistration-certificate` produces a cert like  `[7, [0, h'23BCF2892E8182A68E3AAC6F9F42ED3317D115EBAD12A17232681175'], 0]` which is the new type introduced in Conway  https://github.com/input-output-hk/cardano-ledger/blob/ac5c7f1288daf4bcfdfc0e80cbda22aaa7d6d9d3/eras/conway/impl/cddl-files/conway.cddl#L303
Old stake registration certificate will be deprecated after Conway, see https://github.com/input-output-hk/cardano-ledger/blob/ac5c7f1288daf4bcfdfc0e80cbda22aaa7d6d9d3/eras/conway/impl/cddl-files/conway.cddl#L291

**Comment by gitmachtl** [comment]
the generated certificate is fine, but the type in the output json should be written out as `CertificateConway` imo

**Comment by gitmachtl** [comment]
https://github.com/input-output-hk/cardano-api/pull/390#issuecomment-1836793034

**Comment by smelc** [comment]
@gitmachtl> can you confirm this is fixed?

**Comment by gitmachtl** [comment]
i have a variety of cardano-cli versions from different PRs here, the one that has the fix in it is

cardano-cli 8.18.0.0 - linux-x86_64 - ghc-8.10
git rev 21a75d2dfea2dd61b72904d7f9a990df420522a6

but that build is not here anymore.

i have not tried the latest `main` today

all other versions i have are still outputing "shelleycertificate"

let me compile current `main` ... will report back in a bit.

**Comment by gitmachtl** [comment]
@smelc ok, latest `main`

cardano-cli 8.19.0.0 - linux-x86_64 - ghc-8.10
git rev b228e83b97a45e3b29a85d3ec12a6b95eccafb68

is looking ok!

**Comment by smelc** [comment]
Thanks @gitmachtl :pray: I'm hence closing this issue :+1:
