### ISSUE TITLE
`transaction calculate-min-fee` fails with missing `extraPraosEntropy` key

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-cli#472]
## Description

The `transaction calculate-min-fee` command fails on current `main` with "extraPraosEntropy" not found in protocol parameters file that was generated on latest cardano-node.

## Steps to Reproduce

> cardano-cli transaction calculate-min-fee --testnet-magic 42 --protocol-params-file pparams.json --tx-in-count 1 --tx-out-count 3 --witness-count 23 --byron-witness-count 0 --tx-body-file transfer-register-delegate-fee-tx.txbody

> Command failed: transaction calculate-min-fee  Error: Error while decoding the protocol parameters at: "/home/martink/Source/repos/cardano-node/state-cluster0/pparams.json" Error: "Error in $: key \"extraPraosEntropy\" not found"

The protocol parametrs were created in Shelley era.

## Additional Context

cardano-node: 34d89af65439db92293b88967c299c20692abc1c

Files used for the command: [calculate_fee_error.tar.gz](https://github.com/input-output-hk/cardano-cli/files/13440808/calculate_fee_error.tar.gz)

**Comment by smelc** [comment]
Confirm I can reproduce as of 974946afaf7c2e3ad661e99697b2d390eaa568a1. Thanks @mkoura for the detailed reproducing procedure :handshake:

**Comment by smelc** [comment]
@mkoura> how did you generate the `pparams.json` file? Because indeed, it misses the `extraPraosEntropy` field.

**Comment by gitmachtl** [comment]
@mkoura did you use the new era based commands? its strange, because your pparams.json is missing a lot of information.

**Comment by mkoura** [comment]
I used `cardano-cli query protocol-parameters`. Using `cardano-cli shelley query protocol-parameters` has the same outcome. The important detail is that

> The protocol parametrs were created in Shelley era.

The failure now happens when setting up a testnet that starts in Byron and goes to Babbage by update proposals.
