### ISSUE TITLE
Revamp the create-staked command, to make its output easier to consume

### ISSUE THREAD

**Issue by smelc** [input-output-hk/cardano-cli#473]
As of f1bed2f0e30591a0f5e76856b3389ab4709ab7f1, `cabal run cardano-cli -- genesis create-staked --genesis-dir . --testnet-magic 42 --gen-pools 2 --gen-stake-delegs 2 --gen-utxo-keys 2` generates the following directory:

```shell
> tree
.
├── delegate-keys
│   ├── delegate1.counter
│   ├── delegate1.kes.skey
│   ├── delegate1.kes.vkey
│   ├── delegate1.skey
│   ├── delegate1.vkey
│   ├── delegate1.vrf.skey
│   ├── delegate1.vrf.vkey
│   ├── delegate2.counter
│   ├── delegate2.kes.skey
│   ├── delegate2.kes.vkey
│   ├── delegate2.skey
│   ├── delegate2.vkey
│   ├── delegate2.vrf.skey
│   ├── delegate2.vrf.vkey
│   ├── delegate3.counter
│   ├── delegate3.kes.skey
│   ├── delegate3.kes.vkey
│   ├── delegate3.skey
│   ├── delegate3.vkey
│   ├── delegate3.vrf.skey
│   ├── delegate3.vrf.vkey
│   ├── opcert1.cert
│   ├── opcert2.cert
│   └── opcert3.cert
├── genesis.alonzo.json
├── genesis.alonzo.spec.json -> ../cardano-cli/test/cardano-cli-golden/files/input/alonzo/genesis.alonzo.spec.json
├── genesis.conway.json
├── genesis.conway.spec.json -> ../cardano-cli/test/cardano-cli-golden/files/input/conway/genesis.conway.spec.json
├── genesis.json
├── genesis-keys
│   ├── genesis1.skey
│   ├── genesis1.vkey
│   ├── genesis2.skey
│   ├── genesis2.vkey
│   ├── genesis3.skey
│   └── genesis3.vkey
├── genesis.spec.json
├── pools
│   ├── cold1.skey
│   ├── cold1.vkey
│   ├── cold2.skey
│   ├── cold2.vkey
│   ├── kes1.skey
│   ├── kes1.vkey
│   ├── kes2.skey
│   ├── kes2.vkey
│   ├── opcert1.cert
│   ├── opcert1.counter
│   ├── opcert2.cert
│   ├── opcert2.counter
│   ├── staking-reward1.skey
│   ├── staking-reward1.vkey
│   ├── staking-reward2.skey
│   ├── staking-reward2.vkey
│   ├── vrf1.skey
│   ├── vrf1.vkey
│   ├── vrf2.skey
│   └── vrf2.vkey
├── stake-delegator-keys
└── utxo-keys
    ├── utxo1.skey
    ├── utxo1.vkey
    ├── utxo2.skey
    └── utxo2.vkey
```

That's not very easy to consume for `cardano-testnet`. This issue keeps track of doing better.

**Comment by smelc** [comment]
@carlhammann and I sit together to see how to improve, and here's what we propose:

First, include more directories in the generated structure, so that `cardano-testnet` can have a few loading functions, that take a directory filepath, and loads the data in that directory. Here's the output structure we suggest, in pseudo [BNF format](https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form):

```text
root := delegate-keys/    delegate[0-9]+/ delegate-content
      | genesis-keys/     genesis[0-9]+   genesis-content
      | pools-keys/       pool[0-9]+/     pools-content
      | stake-delegators/ delegator[0-9]+ delegator-content
      | utxo-keys/        utxo[0-9]+/     utxo-content
delegate-content  ::= kes.(skey.vkey)* | opcert.(cert,counter) | vrf.(skey,vkey)
delegator-content ::= payment.(skey,vkey) | staking.(skey,vkey)
genesis-content   ::= genesis.(skey,vkey)
pools-content     ::= cold.(skey|vkey) kes.(skey,vkey) opcert.(cert|counter) staking_reward.(skey,vkey) vrf.(skey,vkey)
utxo-content      ::= utxo.(skey,vkey)
```

In `root`, the atoms ending with `/` denote a directory, while the `*-content` rules denote the contents of a directory. The idea with this grammar is that, to load the output of `create-staked`, it would be sufficient to pass to `cardano-testnet` the list of directories to load (for some definition of "loading").

To do that, there are two routes:

1. Rely on convention, e.g. if a directory filepath matches `utxo-keys/utxo[0-9]+`, load it as if it contained UTxO keys.
2. Have `create-staked` output a JSON file listing the directories, with their kinds. Something like:

```json
{ "utxo-keys/utxo1": "utxo",
  "utxo-keys/utxo2": "utxo",
  "genesis-keys": "genesis" }
```
3. Be more bulletproof, and instead of generating directories, generate a fat JSON file containing the contents of the files, and actually have `cardano-testnet` consume that. Considerations:
    1. Upside is that it's more robust (but all this is test code, so not that important IMHO)
    1. Downside is that it's more work; and we'll have to unpack this big JSON file anyway when executing commands (and to debug failures).

Conclusion of all this is that, Carl and I propose to:

1. Change `create-staked` so that it generates its output according to the grammar specified above. We expect to run into corner cases (because we don't understand well all type of keys) not covered in this issue, that's fine, we'll adapt. @smelc does the implementation.
2. Extend `cardano-testnet` so that it implements the route 2. above. We think this route is a good compromise between going fast and being safe. If we fancy route 3., we can anyway do it later, as it is an extension. @carlhammann does the implementation.

**Comment by Jimbo4350** [comment]
Nice work :+1: . I like the proposed structure. Your proposed path forward sounds good to me. However I would by default not output the directory JSON file and have a flag to enable this.

This doesn't prevent this work from starting however some investigation needs to be done to determine if we are using all the `delegate-keys` content. Some of it may be unnecessary i.e the pool related things such as vrf key, op certs etc. We are already directly injecting stake pool information into the Shelley genesis.

**Comment by smelc** [comment]
> However I would by default not output the directory JSON file and have a flag to enable this.

@Jimbo4350> so you mean using only conventions in the names of the directories to know what to do in `cardano-testnet`? (I means route 1. in this [comment above](https://github.com/input-output-hk/cardano-cli/issues/473#issuecomment-1822939232), not route 2, right?)

> Some of it may be unnecessary i.e the pool related things such as vrf key, op certs etc.

Yeah we suppose we will discover things like this as we go. It's okay, we can adapt on the way.

**Comment by Jimbo4350** [comment]
> > However I would by default not output the directory JSON file and have a flag to enable this.
> 
> @Jimbo4350> so you mean using only conventions in the names of the directories to know what to do in `cardano-testnet`? (I means route 1. in this [comment above](https://github.com/input-output-hk/cardano-cli/issues/473#issuecomment-1822939232), not route 2, right?)
> 
> > Some of it may be unnecessary i.e the pool related things such as vrf key, op certs etc.
> 
> Yeah we suppose we will discover things like this as we go. It's okay, we can adapt on the way.

I've thought about it some more. This should be a new command and we should deprecate create-staked. 

>  1. Change create-staked so that it generates its output according to the grammar specified above. We expect to run into corner cases (because we don't understand well all type of keys) not covered in this issue, that's fine, we'll adapt. @smelc does the implementation.
> 2. Extend cardano-testnet so that it implements the route 2. above. We think this route is a good compromise between going fast and being safe. If we fancy route 3., we can anyway do it later, as it is an extension. @carlhammann does the implementation.

^^ What you suggested sounds good. However it should be done as a separate command so we don't immediately break things for users or over complicate the code by trying to remain backwards compatible.

**Comment by Jimbo4350** [comment]
Sam requested the following for the new command:
> Can you make create -staked use the same keys for Byron and Shelley genesis and alter it to take template files instead of assuming spec files are in current directory?? If you did that and it optionally took a staked genesis we could probably switch to it and consolidate.

**Comment by carlhammann** [comment]
@smelc We forgot the `opcert.(cert|counter)` and the `delegate.(skey|vkey)` for the `delegate-content` in the "grammar" above.

**Comment by newhoggy** [comment]
I reckon it would be good if `create-staked` create a file that describe what files it created.

This would help discover the new files and serve as a record of what happened in large tests.

Another benefit is that this output is golden testable so if we every change what files were produced, it would be very visible in PRs.

**Comment by smelc** [comment]
@newhoggy> good point :+1: I'll make the generation of this file optional (and turned off by default), so that we can indeed use it in tests.

**Comment by smelc** [comment]
> @smelc We forgot the opcert.(cert|counter) and the delegate.(skey|vkey) for the delegate-content in the "grammar" above.

@carlhammann> I updated the grammar :+1:

**Comment by CarlosLopezDeLara** [comment]
Discussing this with @Jimbo4350 he came up with a glorious idea of having an option to write (or not) the delegated keys to disk. The current behavior is that it does not write them to disk after a request from the benchmarking team. Having this as an option gives us more flexibility for other use cases (i.e. tests) where we do need the stake keys available.

**Comment by smelc** [comment]
@CarlosLopezDeLara> can you be more specific at what keys are missing? Right now the output is looking like this:

[edit] Carlos answered here: https://input-output-rnd.slack.com/archives/C031GFLC3DF/p1701118783237699

```
test_out
├── delegate-keys
│   ├── delegate1
│   │   ├── kes.skey
│   │   ├── kes.vkey
│   │   ├── key.skey
│   │   ├── key.vkey
│   │   ├── opcert.cert
│   │   ├── opcert.counter
│   │   ├── vrf.skey
│   │   └── vrf.vkey
│   └── delegate2
│       ├── kes.skey
│       ├── kes.vkey
│       ├── key.skey
│       ├── key.vkey
│       ├── opcert.cert
│       ├── opcert.counter
│       ├── vrf.skey
│       └── vrf.vkey
├── genesis-keys
│   ├── genesis1
│   │   ├── genesis.skey
│   │   └── genesis.vkey
│   └── genesis2
│       ├── genesis.skey
│       └── genesis.vkey
├── genesis-shelley.json
├── pools-keys
│   ├── pool1
│   │   ├── cold.skey
│   │   ├── cold.vkey
│   │   ├── kes.skey
│   │   ├── kes.vkey
│   │   ├── opcert.cert
│   │   ├── opcert.counter
│   │   ├── staking-reward.skey
│   │   ├── staking-reward.vkey
│   │   ├── vrf.skey
│   │   └── vrf.vkey
│   └── pool2
│       ├── cold.skey
│       ├── cold.vkey
│       ├── kes.skey
│       ├── kes.vkey
│       ├── opcert.cert
│       ├── opcert.counter
│       ├── staking-reward.skey
│       ├── staking-reward.vkey
│       ├── vrf.skey
│       └── vrf.vkey
└── utxo-keys
    ├── utxo1
    │   ├── utxo.skey
    │   └── utxo.vkey
    ├── utxo2
    │   ├── utxo.skey
    │   └── utxo.vkey
    └── utxo3
        ├── utxo.skey
        └── utxo.vkey
```
