### ISSUE TITLE
output of `query protocol-parameters` is missing `protocolVersion`

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-cli#474]
## Description

A `protocolVersion` section is now missing from the output of `query protocol-parameters`.

There used to be a section like

```json
"protocolVersion": {
  "major": 8,
  "minor": 0
}
```

## Steps to Reproduce

Run
`cardano-cli query protocol-parameters --testnet-magic 42`
or
`cardano-cli babbage query protocol-parameters --testnet-magic 42`
and check that "protocolVersion" is missing.

## Additional Context

```
cardano-cli --version
cardano-cli 8.15.0.0 - linux-x86_64 - ghc-8.10
git rev 34d89af65439db92293b88967c299c20692abc1c
```

```
$ cardano-node --version
cardano-node 8.7.0 - linux-x86_64 - ghc-8.10
git rev 34d89af65439db92293b88967c299c20692abc1c
```

protocol parameters generated in Babbage: [pparams.json](https://github.com/input-output-hk/cardano-cli/files/13442582/pparams.json)

**Comment by gitmachtl** [comment]
hmm, are those errors now with the protocolparameters coming from the change in https://github.com/input-output-hk/cardano-cli/pull/455 ? @CarlosLopezDeLara 

also missing f.e. `monetaryExpansion`

**Comment by CarlosLopezDeLara** [comment]
> hmm, are those errors now with the protocolparameters coming from the change in #455 ? @CarlosLopezDeLara
> 
> also missing f.e. `monetaryExpansion`

most likely!

**Comment by smelc** [comment]
@gitmachtl> #455 was reverted in the end, so it this issue still occurring on `HEAD`?

If yes, it's likely unrelated to #455.

**Comment by mkoura** [comment]
Already fixed.
