### ISSUE TITLE
Missing tests for  online commands

### ISSUE THREAD

**Issue by carlhammann** [input-output-hk/cardano-cli#477]
This is a pretty big one: Currently, AFAICT, all commands that need to interact with a running node have no tests. This group of commands contains
- all queries
- transaction building (with `build`, not `build-raw`)
- transaction submission

I'll split this issue up into smaller ones, but thought it worthwhile to have the big one as a reminder.

**Comment by smelc** [comment]
There are a few such tests in cardano-node already, and we are in the process of adding more, as part of the Conway testing roadmap. So closing.
