### ISSUE TITLE
`ShelleyEncoderUnsupportedQuery` error when running `query stake-address-info` in Babbage

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-cli#480]
## Description

In Babbage era, the `cardano-cli query stake-address-info` now fails with

> cardano-cli: ShelleyEncoderUnsupportedQuery (SomeSecond (GetFilteredVoteDelegatees (fromList [KeyHashObj (KeyHash "e9a7fb37a6f15c7e53b65a560fe1e647e682f6ecb8785ce1033d4a66")]))) ShelleyNodeToClientVersion7

## Steps to Reproduce

Run

> cardano-cli query stake-address-info --address stake_test1ur5607eh5mc4cljnked9vrlpuer7dqhkaju8sh8pqv755esy0dlft --testnet-magic 42

## Additional Context

cardano-cli rev: c50683fe91d98fb6ab12461902301df3b505e9cc
cardano-node rev: 49e39d29c5eebc385c384d7edf752ebe47fa1a7f

**Comment by carbolymer** [comment]
Related changes:
* https://github.com/input-output-hk/cardano-cli/pull/452
* https://github.com/input-output-hk/cardano-api/pull/367
* https://github.com/input-output-hk/ouroboros-consensus/pull/502#discussion_r1389416864

Original feature request: https://github.com/input-output-hk/cardano-cli/issues/423

**Comment by carlhammann** [comment]
Whoops, that was my mess! I'm just catching up with this now. Can't we solve this by just disabling [this query](https://github.com/input-output-hk/cardano-cli/blob/c50683fe91d98fb6ab12461902301df3b505e9cc/cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs#L817) in pre-Conway eras?

**Comment by carbolymer** [comment]
@carlhammann no worries. Yes, that will do the trick. I'm working on a more general solution atm. I'll push the fix soon.
