### ISSUE TITLE
[BUG] - `cardano-cli ping --unixsock` not sending pings

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-cli#49]
## Description

The `cardano-cli ping --unixsock` is not sending pings. The behavior doesn't seem to correspond with the command name as is potentially confusing for end user.

```
$ cardano-cli ping --count 5 --unixsock /home/martink/Source/repos/cardano-node/state-cluster0/bft1.socket --magic 42 --json
/home/martink/Source/repos/cardano-node/state-cluster0/bft1.socket network rtt: 0.000
/home/martink/Source/repos/cardano-node/state-cluster0/bft1.socket handshake rtt: 0.000188265s
/home/martink/Source/repos/cardano-node/state-cluster0/bft1.socket Negotiated version NodeToClientVersionV16 42
] }
```

Also notice the confusing json output.

Tested with cardano-cli 8.2.1 on Linux.

---

**[edit]** after discussions with @mkoura and @coot. We will:

* Introduce a new `handshake` command that works for both node-to-client and node-to-node.
* Remove the `--unixsock` option from `ping`

---

**[edit]** after review by @Jimbo4350 [here](https://github.com/input-output-hk/cardano-cli/pull/468#discussion_r1402195666), we finally decided to:

* Introduce a new `--handshake-only` flag to `ping`
* Make `-u/--unixsock` work only with `--handshake-only` (i.e. `--unixsock` is conditioned by presence of `--handshake-only` is specified)
* Deprecate `-Q/--query-versions` in `ping`. `-Q` should preferably be used with `--handshake-only`.

**Comment by smelc** [comment]
Explanation for the confusing json output (trailing `] }`): https://github.com/input-output-hk/cardano-cli/issues/197#issuecomment-1723419123

**Comment by smelc** [comment]
Since this issue was opened, the output was jsonified: https://github.com/input-output-hk/cardano-cli/pull/411, albeit the crux of this issue is still there.

**Comment by smelc** [comment]
Can reproduce as of 04b1ccf1fc79864b52052138ae1e127ddf853fe9:

```shell
→ cabal run cardano-cli -- ping -u $HOME/dev/sanchonet/node.socket --magic 4 -j
/home/churlin/dev/sanchonet/node.socket {"network_rtt":1.1953e-5}
/home/churlin/dev/sanchonet/node.socket {"handshake_rtt":1.48992e-4}
/home/churlin/dev/sanchonet/node.socket {"negotiated_version":{"magic":4,"version":"NodeToClientVersionV16"}}
] }
```

**Comment by smelc** [comment]
That's because [this conditional in ourboros-network](https://github.com/input-output-hk/ouroboros-network/blob/34f995567eb2ef3340a1714734ec0d2df5a0970b/cardano-ping/src/Cardano/Network/Ping.hs#L564)  is not entered in the case where `isUnixSocket` holds.

If I remove the `isUnixSocket` condition, then `cardano-cli ping` fails as follows:

```shell
> cabal run cardano-cli -- ping -u $HOME/dev/sanchonet/node.socket --magic 4 -c 5 -j
/home/churlin/dev/sanchonet/node.socket {"network_rtt":1.3868e-5}
/home/churlin/dev/sanchonet/node.socket {"handshake_rtt":3.25788e-4}
pintOptsHandshakeQuery: False
querySupported: True
isUnixSocket: True
/home/churlin/dev/sanchonet/node.socket {"negotiated_version":{"magic":4,"version":"NodeToClientVersionV16"}}
] }
(AddrInfo {addrFlags = [], addrFamily = AF_UNIX, addrSocketType = Stream,
 addrProtocol = 0, addrAddress = /home/churlin/dev/sanchonet/node.socket, addrCanonName = Nothing},
 MuxError MuxBearerClosed "<socket: 11> closed when reading data, waiting on next header True")
```

But at this point, I need to spend more time digging whether the `ping` protocol can be supported in the case of Unix sockets. This is probably normal that this doesn't work, in which case the user-facing UI of `cardano-cli ping` needs to be amended, to avoid looking like it supports it, whereas it doesn't.

I'll ask @coot to fill me in and update here accordingly. Expect some delay.

**Comment by coot** [comment]
@mkoura the `node-to-client` protocol doesn't include `keep-alive` mini-protocol, only `node-to-node` does, so there's no way to send `pings` on a unix socket.  The command is still useful for `node-to-client`, as it allows to debug connectivity / version mismatch issues.  One possible solution would be to simply expose a `cardano-cli handshake` command which negotiate the connection and limit `ping` to `node-to-node`.
