### ISSUE TITLE
[BUG] - all zeros git revision reported by `--version`

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-cli#50]
## Description

When building cardano-cli using nix, git rev is all zeros:

```
$ nix build .#cardano-cli -o cardano-cli-build
$ ./cardano-cli-build/bin/cardano-cli --version
cardano-cli 8.2.1 - linux-x86_64 - ghc-9.2
git rev 0000000000000000000000000000000000000000
```

I'm using cardano-cli 8.2.1 release on Linux.

**Comment by CarlosLopezDeLara** [comment]
issue still present in 

```
./cardano-cli --version
cardano-cli 8.18.0.0 - linux-x86_64 - ghc-9.2
git rev 0000000000000000000000000000000000000000
```

**Comment by sgillespie** [comment]
I would guess that the nix code to do this can be copied from:

https://github.com/IntersectMBO/cardano-node/blob/76ef0fe7cd716426e41813958569521dd80cda8b/flake.nix#L134
