### ISSUE TITLE
Cannot create UTxO with datum hash using Alonzo era Tx

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-cli#501]
## Description

When building Alonzo era Tx, datum seems to be ignored. Resulting UTxO is missing datum hash.

This can lead to unspendable UTxOs.

Babbage era transactions are ok.

## Steps to Reproduce
1. create UTxO with datum
> cardano-cli transaction build-raw --fee 206493 --out-file "test_txout_locking[plutus_v1]_ci0_wvv_step1_tx.body" --tx-in "4704d8ca62202aa08430f4646a369b5e4a4edb0b253b3c73a703306144153b94#0" --tx-out "addr_test1wpnlxv2xv9a9ucvnvzqakwepzl9ltx7jzgm53av2e9ncv4sysemm8+2400250" --tx-out-datum-hash-file typed-42.datum --tx-out "addr_test1vqywhyg482c5pmex624cdtslx2tm3ghgd9zwqkgauzjc69s98xmzl+2000000" --tx-out "addr_test1vrgc5nsf857gs5qm0j6j3xvekmzpljedd8y6207z6lh5rms4695pq+2995393257" --alonzo-era

> cardano-cli transaction sign --tx-body-file "test_txout_locking[plutus_v1]_ci0_wvv_step1_tx.body" --testnet-magic 42 --signing-key-file "test_txout_locking[plutus_v1]_ci0_hpl_payment_addr_0.skey" --out-file "test_txout_locking[plutus_v1]_ci0_wvv_step1_tx.signed

> cardano-cli transaction submit --testnet-magic 42 --tx-file "test_txout_locking[plutus_v1]_ci0_wvv_step1_tx.signed

2. check the UTxO that should have the datum

> cardano-cli query utxo --out-file /dev/stdout --tx-in "828a33d6087af73412bc307f84223690cfae853b341f19990ed86e0606d8e593#0" --testnet-magic 42

```json
{
    "828a33d6087af73412bc307f84223690cfae853b341f19990ed86e0606d8e593#0": {
        "address": "addr_test1wpnlxv2xv9a9ucvnvzqakwepzl9ltx7jzgm53av2e9ncv4sysemm8",
        "datum": null,
        "datumhash": null,
        "inlineDatum": null,
        "referenceScript": null,
        "value": {
            "lovelace": 2400250
        }
    }
}
```

See that the datum is missing, even though it should be there.

3. try to spend the locked UTxO

> cardano-cli transaction build-raw --fee 400250 --out-file "test_txout_locking[plutus_v1]_ci0_wvv_step2_tx.body" --tx-in "828a33d6087af73412bc307f84223690cfae853b341f19990ed86e0606d8e593#0" --tx-in-script-file always-succeeds-spending.plutus --tx-in-execution-units "(368100,1700)" --tx-in-datum-file typed-42.datum --tx-in-redeemer-cbor-file 42.redeemer.cbor --tx-in-collateral "828a33d6087af73412bc307f84223690cfae853b341f19990ed86e0606d8e593#1" --protocol-params-file pparams-tmcc.json --tx-out "addr_test1vqywhyg482c5pmex624cdtslx2tm3ghgd9zwqkgauzjc69s98xmzl+2000000" --alonzo-era

> cardano-cli transaction sign --tx-body-file "test_txout_locking[plutus_v1]_ci0_wvv_step2_tx.body" --testnet-magic 42 --signing-key-file "test_txout_locking[plutus_v1]_ci0_hpl_payment_addr_1.skey" --out-file "test_txout_locking[plutus_v1]_ci0_wvv_step2_tx.signed

> cardano-cli transaction submit --testnet-magic 42 --tx-file "test_txout_locking[plutus_v1]_ci0_wvv_step2_tx.signed

See an error

> Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (AlonzoInBabbageUtxowPredFailure (UnspendableUTxONoDatumHash (fromList [TxIn (TxId {unTxId = SafeHash "828a33d6087af73412bc307f84223690cfae853b341f19990ed86e0606d8e593"}) (TxIx 0)]))),UtxowFailure (AlonzoInBabbageUtxowPredFailure (NotAllowedSupplementalDatums (fromList [SafeHash "fcaa61fb85676101d9e3398a484674e71c45c3fd41b492682f3b0054f4cf3273"]) (fromList [])))])

The UTxO is unspendable.

Files used for building the Tx: [alonzo_tx.tar.gz](https://github.com/input-output-hk/cardano-cli/files/13562568/alonzo_tx.tar.gz)

## Additional Context

Tested with cardano-node 8.7.1-pre

**Comment by carbolymer** [comment]
> Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (AlonzoInBabbageUtxowPredFailure (UnspendableUTxONoDatumHash (fromList [TxIn (TxId {unTxId = SafeHash "17d680bf9d7173a8e55b81e6d1c42aab490603bcebaf9f33d46c3478085881a8"}) (TxIx 0)]))),UtxowFailure (AlonzoInBabbageUtxowPredFailure (NotAllowedSupplementalDatums (fromList [SafeHash "fcaa61fb85676101d9e3398a484674e71c45c3fd41b492682f3b0054f4cf3273"]) (fromList [])))])

**Comment by Jimbo4350** [comment]
@carbolymer You first need to put a datum at a Plutus script address.

**Comment by Jimbo4350** [comment]
Fixed by https://github.com/input-output-hk/cardano-api/pull/398
