### ISSUE TITLE
stake-address registration-certificate has the flag --key-reg-deposit-amt, it should not.

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#504]
legacy command 

`cardano-cli stake-address registration-certificate 
`
and era based 

`cardano-cli babbage stake-address registration-certificate `

have the flag `--key-reg-deposit-amt` but it is really not needed on Babbage. This is purely cosmetic since the resulting certificate does conform to the Babbage cddl. In other words, using this flag does not have any impact but might be confusing, since the deposit in Babbage era should be supplied on the pre-conway fashion: when balancing the transaction.   So it would be good to remove the flag for Babbage era and legacy

---

Clarification [here on Slack](https://input-output-rnd.slack.com/archives/C031GFLC3DF/p1702302426416769): `--key-reg-deposit-amt` should only be present in `conway`.

**Comment by smelc** [comment]
@CarlosLopezDeLara> PR is at https://github.com/input-output-hk/cardano-cli/pull/509

:warning: The PR only changes the parser for `babbage stake-address registration-certificate`. I can't modify the legacy parser (no matter if the era is omitted, or if `--babbage-era` is passed). We're touching here _the_ fundamental difference between the era based parser and the legacy ones: era based parsers can be made era-specific, while the legacy ones cannot (see [discussion on Slack](https://input-output-rnd.slack.com/archives/C031GFLC3DF/p1701888593066159?thread_ts=1701881107.965289&cid=C031GFLC3DF)).
