### ISSUE TITLE
`calculate-min-fee` with signed transaction body

### ISSUE THREAD

**Issue by felix-lipski** [input-output-hk/cardano-cli#543]
The `calculate-min-fee` command should support the following scenarios:

1. The user submits an unsigned tx body specifying the number of byron/shelley witnesses they desire.
    - In the cli we construct dummy witnesses (byron if needed ~~or shelley or both~~) to construct a "bogus" tx and call `getMinFeeTx`. We return only the fee in this case otherwise the users will have to remove the bogus witnesses if we returned the resulting tx. Constructing the dummy witnesses will allow us to avoid implementing something like `calculateByronWitnessFees`.
    
2. The user submits a signed tx or an unsigned tx body _along with the signing keys_ they intend to validate the tx with.
    - In this case we should return the _re-signed_ transaction. The transaction has to be re-signed after the minimum fee is updated and the user will receive a valid tx they can immediately submit.
    - Consider returning an error if the number of witnesses in the signed tx does not equal the number of signing keys (0 supplied signing keys is fine and is actually the third scenario).
    
3. The user submits a signed tx _without the signing keys needed to validate the tx_. We simply return the fee as we can't return a valid tx.

As referenced in [this comment on PR#534](https://github.com/IntersectMBO/cardano-cli/pull/534#issuecomment-1874261228)

**_The first scenerio is currently being worked on/completed. This issue only pertains to the second and third scenerio._**

**Comment by smelc** [comment]
Not sure what we want to do with this one. The thread that started this stream of work got quite deep: https://github.com/IntersectMBO/cardano-cli/pull/534

cc @Jimbo4350
