### ISSUE TITLE
[FR] - include the stake-distribution within the drep-state query

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-cli#551]
To get the whole information about a drep keyHash, we have to make two queries:
1. query the `drep-state`
```json
[
    [
        {
            "keyHash": "2c0e9f599655bd3f7f313a3a61fe05fb9caac4cc3d1aa77740fc9579"
        },
        {
            "anchor": null,
            "deposit": 2000000,
            "expiry": 223
        }
    ]
]
```
2. query the `drep-stake-distribution`
```json
[
    [
        "drep-keyHash-2c0e9f599655bd3f7f313a3a61fe05fb9caac4cc3d1aa77740fc9579",
        1625348
    ]
]
```

Would it be possible to directly have an entry for the currently delegated amount within the `drep-state` output?

Like:
```json
[
    [
        {
            "keyHash": "2c0e9f599655bd3f7f313a3a61fe05fb9caac4cc3d1aa77740fc9579"
        },
        {
            "anchor": null,
            "deposit": 2000000,
            "expiry": 223
        },
        {
            "delegation": 1625348
        }
    ]
]
```
or similar?

**Comment by smelc** [comment]
cc @CarlosLopezDeLara @carlhammann

**Comment by carlhammann** [comment]
From the perspective of the code in the cardano-cli, the proposed change should be fairly easy. I'll investigate why the two queries are exposed separately. If it's purely historical, then let's change it; if there are performance reasons, I see no reason in principle why we couldn't have a `--include-stake-distribution` flag with the `drep-state` query (and deprecate the `drep-stake-distribution` query?).

**Comment by carlhammann** [comment]
OK, the reason is performance: https://github.com/IntersectMBO/ouroboros-consensus/blob/404aaec8a4c8091594b4bc5a38e26f6ea9627f6b/ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Query.hs#L254

In that case, I think a flag as I proposed in my last comment with an appropriate warning would be an acceptable solution.
