### ISSUE TITLE
[FR] - include governance parameters also in the protocol-parameters query

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-cli#554]
```console
$ cardano-cli version
cardano-cli 8.17.0.0 - linux-x86_64 - ghc-8.10
git rev a4a8119b59b1fbb9a69c79e1e6900e91292161e7
```

Is it possible to also include the current governance related parameters directly into the procotol-parameters query?

For example, currently we have to do a 
```bash
cardano-cli conway query protocol-parameters
```
action to get the general parameters for building a tx.

And when we do for example a DRep-ID registration we need to also do a
```bash
cardano-cli conway query gov-state | jq -r ".enactState.curPParams"
```
command to get mostly the same values (not all) and the additional ones to do correct transactions for the new conway stuff.

So it would be supernice if the current governance parameters would also be included in the protocol-parameters query to just have one query that shows all current parameters set.

**Comment by carlhammann** [comment]
I'm re-opening this in the light of [this discussion](https://github.com/IntersectMBO/cardano-cli/pull/569#issuecomment-1895636548).

**Comment by smelc** [comment]
Closing as duplicate of https://github.com/IntersectMBO/cardano-cli/issues/729

Updates will be posted on https://github.com/IntersectMBO/cardano-cli/issues/729 instead
