### ISSUE TITLE
[FEATURE] -  Add support for registering scripts as DReps.

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#559]
## What
Add support for registering scripts as DReps. 

Expand `cardano-cli conway governance drep registration-certificate` so that it can also take `--script-file` and `--script-hash` as inputs. 

The new flags should be alternatives to the existing --drep-verification-key, --drep-verification-key-file, and --drep-key-hash  

The resulting certificate must comply with the conway cddl, where: 

```
reg_drep_cert = (16, drep_credential, coin, anchor / null)

drep_credential = credential

credential =
  [  0, addr_keyhash
  // 1, scripthash
  ]
```

## Why
From CIP1694

> Registered DReps are identified by a credential that can be either:
> 
> A verification key (Ed25519)
> A native or Plutus script

## Personas

- [ ] SPOs
- [ ] dApp Devs
- [ ] Exchanges
- [ ] Wallets
- [ ] 3rd party tools
- [x] ADA holders 
- [x] DReps

## Definition of Done (DoD)

- [ ] [Acceptance Criteria + User Stories & DoD](https://input-output.atlassian.net/wiki/spaces/QA/pages/3584229468/Acceptance+Criteria+DoD) created and singed-off (by PO, dev & test owners)
- [ ] Builds successfully on CI
- [ ] Code & Test review (as per Acceptance Criteria)
- [ ] There is documentation and/or examples for the new functionality (usage/response)
- [ ] Log/record changes on **Vnext** (or similar depending on what we adopt)
- [ ] Ticket number(s) included in PR description
- [ ] All Acceptance Criteria met and covered by dev/unit/property/integration tests
- [ ] System/E2E automated tests + System Test Engineer Owner Sign-off

> **_NOTE:_**  Ideally, we should merge only fully implemented and tested features into the master branch. 
> So all the above steps are required for the PR to be merged.  
> In order to avoid the PRs becoming stale and requiring to be rebased on master, these can be merged 
> after a reasonable time (current agreement is 3 days) if the System Test Engineer Owner's sign-off 
> was not provided (last step in the DoD).

> **_IMPORTANT:_** Any deviation from the plan should be discussed and agreed as a comment in the Feature file. 

## Sign-off

- [ ] Product Owner
- [ ] Dev Owner
- [ ] System Test Engineer Owner

# Related PRs

1.  PR # here

**Comment by carlhammann** [comment]
We'll also have to make sure that the filtering by DRep credential done in the `drep-state` and `drep-stake-distribution` queries works with scripts __and__ keys.

Edit: I opened an issue: #562
