### ISSUE TITLE
Adapt the DRep commands to script credentials in addition to key credentials for DReps

### ISSUE THREAD

**Issue by carlhammann** [input-output-hk/cardano-cli#562]
## Description

This is a follow-up of #559. If we're able to _register_ scripts as DReps, we'll also want to be able to
- _deregister_ them,
- _update_ them (see #550), and
- filter the queries in `drep-state` and `drep-stake-distribution` with them.

Currently, these capabilities are missing.

**Comment by gitmachtl** [comment]
@carlhammann how would you be able to filter for drep_script if the only value that is stored is the hex hash and not the bech representation? 

i brought this issue up months ago when i invited to take a deeper look on drep ids here on GH. adding one extra byte for additional data like this "drep is a script" right now (similar to addresses). looks like a missed opportunity now.
