### ISSUE TITLE
[FR] - Standardize JSON representations of Cardano domain types

### ISSUE THREAD

**Issue by klntsky** [input-output-hk/cardano-cli#570]
**Internal/External**
*External*

**Area**
*Other*   JSON format standardization

**Describe the feature you'd like**

I am pushing an initiative to standardize JSON representations of Cardano domain types for offchain tooling. See [this CPS](https://github.com/cardano-foundation/CIPs/pull/742) for the motivation.

Ideally the standard should be based on existing and widely used implementations, which `cardano-cli` is one of.

There is, however, an ecosystem-wide problem: standard JSON tooling does not support long integer representations, which makes certain values unrepresentable when encoding of long integers to numbers is used. For example, see [the comments for JSON machinery in CSL](https://github.com/Emurgo/cardano-serialization-lib/blob/4a35ef11fd5c4931626c03025fe6f67743a6bdf9/rust/src/plutus.rs#L1091), and [this issue](https://github.com/Emurgo/cardano-serialization-lib/issues/658).

Would it be possible to avoid encoding long integers as JSON numbers and switch to strings? That would allow tools like CSL (and literally any other offchain library) to be fully compatible.

Additionally, I have a few other questions:

- Is there a way to get JSON schemas of the current encoding without diving into the code?

- Does it make sense to standardize `cardano-cli` format from your point of view?

**Describe alternatives you've considered**

The alternative would be to define a standard that is not compatible with cardano-cli.

**Comment by gitmachtl** [comment]
The "long number" issue, at least for the cli and the widely used tool `jq` can be avoided by a simple convert like:

Normal output:

```console
./cardano-cli query utxo --address $(cat funds.addr) --out-file /dev/stdout | jq
```
```json
{
  "040e17a156ebc4417abf03b89ded5cef7b44f67a090ddf65979eb442cb72fdf7#0": {
    "address": "addr_test1vpfwv0ezc5g8a4mkku8hhy3y3vp92t7s3ul8g778g5yegsgalc6gc",
    "datum": null,
    "datumhash": null,
    "inlineDatum": null,
    "referenceScript": null,
    "value": {
      "lovelace": 9467947941
    }
  }
}
```

Numbers stringified:
```console
./cardano-cli query utxo --address $(cat funds.addr) --out-file /dev/stdout | sed -e 's/": \([0-9]\+\)/": "\1"/g' | jq
```
```json
{
  "040e17a156ebc4417abf03b89ded5cef7b44f67a090ddf65979eb442cb72fdf7#0": {
    "address": "addr_test1vpfwv0ezc5g8a4mkku8hhy3y3vp92t7s3ul8g778g5yegsgalc6gc",
    "datum": null,
    "datumhash": null,
    "inlineDatum": null,
    "referenceScript": null,
    "value": {
      "lovelace": "9467947941"
    }
  }
}
```

Its not a JSON problem, its a problem of some tools reading/processing JSON content. cardano-cli is a CLI tool, so that would be a quick solution for CLI apps.

**Comment by klntsky** [comment]
@gitmachtl It's not that I'm looking for a code solution, the problem is that other tools are unable to parse cardano-cli output or maintain compatibility with it without reinventing the whole JSON encoding stack (like we [did](https://github.com/mlabs-haskell/purescript-aeson/))

**Comment by smelc** [comment]
cc @CarlosLopezDeLara

**Comment by gitmachtl** [comment]
> @gitmachtl It's not that I'm looking for a code solution, the problem is that other tools are unable to parse cardano-cli output or maintain compatibility with it without reinventing the whole JSON encoding stack (like we [did](https://github.com/mlabs-haskell/purescript-aeson/))

yea but the output of cardano-cli is fully JSON compliant as it is. so correct me if i am wrong, but the problem lies in the 3rd party tools parsing JSON correctly. do you have examples on 3rd party tools that are taking the output of cardano-cli and having issues with it? because as i posted above, for JQ the solution is simple. also the readout like "jq -r .keyName" returns the correct output also with lovelaces or native-asset amounts stringified. for JS, people can use the `json-bigint` lib like:

```JS
var JSONbig = require('json-bigint');
let result = JSONbig.parse(<your-json>);
```

if we change the output of cardano-cli to stringified numbers, i am ok with that. i proposed that i think two years ago. the conclusion last time was, that numbers are numbers and should not be stringified. i am not against a stringified number output for cardano-cli.

**Comment by smelc** [comment]
We probably don't want to change the CLI's handling of long integers, because we rely on [aeson](https://hackage.haskell.org/package/aeson-2.2.1.0/docs/Data-Aeson.html) for JSON serialization, and aeson is supposed to honor the JSON specification.

However, there is particularly interesting piece here:

> Is there a way to get JSON schemas of the current encoding without diving into the code?

This is probably something we can do, if our bandwidth allows, because I think it's indeed interesting for users. Which is why I'm removing the _Stale_ label.

**Comment by klntsky** [comment]
> aeson is supposed to honor the JSON specification.

The JSON specification does not define the ranges for allowed numeric types, leaving them platform-dependent. Do we really want to deal with platform-dependent behaviors in our tech stack? Especially given that the price of avoiding them is so low.

The goal of providing the encodings in the first place is interoperability, but as for now it hasn't been achieved, because the spec in fact contains undefined behavior.

> but the problem lies in the 3rd party tools parsing JSON correctly. do you have examples on 3rd party tools that are taking the output of cardano-cli and having issues with it

@gitmachtl yes,

- native `JSON.parse` (nodejs, the browser) - truncates the numbers silently
- Rust's `serde` ([context](https://github.com/Emurgo/cardano-serialization-lib/issues/658))
- probably almost every JSON library in almost every programming language, as long integer arithmetic is not very common to be in the standard library, and is a niche use case - IEEE floats are the default

**Comment by gitmachtl** [comment]
i am not against a stringified output of numbers for json outputs via cardano-cli like the utxo query. but for nodejs there is the json-bigint lib that i wrote about here https://github.com/IntersectMBO/cardano-cli/issues/570#issuecomment-1895433097
browser and cardano-cli is a bit of a strange combination. for bash the `| sed -e 's/": \([0-9]\+\)/": "\1"/g'` method as pipe works pretty fine.

again, i am happy if the decision is made to make the numbers also stringified.

**Comment by klntsky** [comment]
@gitmachtl 

> browser and cardano-cli is a bit of a strange combination

The goal is to make everything mutually compatible: cardano-cli <-> nodejs <-> dApp backend <-> browser <-> wallets <-> wallet backends. That would reduce the amount of code needed to simply pass data between these.

> but for nodejs there is the json-bigint lib

It implements its own string parser which is too costly for the runtime (in comparison with native `JSON.parse`). We use an abstraction on top of its fork, and the amount of time it spends in the parse loop is noticeable in the profiler.

> again, i am happy if the decision is made to make the numbers also stringified.

OK, I'll provide everything I can to increase the chance of it happening. 

Here's a WIP [json-schema](https://github.com/klntsky/CIPs/blob/6da3763c4d69722316e0b7ebbaf9c329e8e19cd0/CIP-XXXX/schema.json) ([branch](https://github.com/klntsky/CIPs/tree/klntsky/json-spec-cip/)) that I'm working on - the goal is to define all structural parts of a Transaction. Then there will be a stage of CIP review - but please don't hesitate to look at this in its current state.

**Comment by smelc** [comment]
@klntsky> thanks for the additional explanations :+1:

Two comments though:

> Do we really want to deal with platform-dependent behaviors in our tech stack? 

Indeed I'm all for being platform agnostic :slightly_smiling_face: 

> Especially given that the price of avoiding them is so low

Not sure about this one :slightly_smiling_face: Staying retro-compatible is important for `cardano-cli` and this would be a pretty big change! cc @Jimbo4350 @CarlosLopezDeLara
