### ISSUE TITLE
Voting on an action as an SPO should use cold SPO vkey

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-cli#58]
## Description

SPO votes take wrong key type. It should only accept cold verification keys of the pool, not a stake.

## Steps to Reproduce

```
result/bin/cardano-cli governance vote create-vote --spo --stake-verification-key-file ~/keys-preview/stake-pools/sp-1-cold.vkey --yes --out-file vote.cert --tx-in 5031183cb5503969a4d738d388b01fc7f029d58ea45b2ce3aace4c52e7e1d078#0
StakeCredGovCmdError (ShelleyStakeAddressCmdReadKeyFileError (FileError "/home/sam/keys-preview/stake-pools/sp-1-cold.vkey" (InputTextEnvelopeError (TextEnvelopeTypeError [TextEnvelopeType "StakeVerificationKeyShelley_ed25519"] (TextEnvelopeType "StakePoolVerificationKey_ed25519")))))
```

## Additional Context

Please provide any additional information that might be helpful, such as the version of Cardano-node you're using, your operating system, etc.

## Possible Solution

If you have a potential solution to the problem, please describe it here.

**Comment by carbolymer** [comment]
There's `conway governance vote create` command supporting this: https://github.com/input-output-hk/cardano-cli/blob/main/cardano-cli/test/cardano-cli-golden/files/golden/help/conway_governance_vote_create.cli
