### ISSUE TITLE
[FR] - Expand action create-protocol-parameters-update to take an optional script hash. 

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#582]
**Internal/External**
*Internal*   if an IOHK staff member.
**Area**
Governance

**Describe the feature you'd like**

Expand `action create-protocol-parameters-update` command to also take an optional scripthash (the policy script, also called guardrails script) of the supplementary script of the constitution.  

conway cddl: 
`parameter_change_action = (0, gov_action_id / null, protocol_param_update, policy_hash / null)`

**Comment by smelc** [comment]
Done by @Jimbo4350 in https://github.com/IntersectMBO/cardano-cli/pull/529
