### ISSUE TITLE
[FR] - Expand action create-treasury-withdrawal to also take an optional scripthash

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#583]
Internal/External
Internal if an IOHK staff member.
Area
Governance

Describe the feature you'd like

Expand action create-treasury-withdrawal command to also take an optional scripthash (the policy script, also called guardrails script) of the supplementary script of the constitution.

```
conway cddl: 
treasury_withdrawals_action = (2, { reward_account => coin }, policy_hash / null)
```

**Comment by smelc** [comment]
Done by @Jimbo4350 in https://github.com/IntersectMBO/cardano-cli/pull/529
