### ISSUE TITLE
[FR] - Switch CLI to have era top-levls

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-cli#59]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Token Locking*    Related to Token Locking (Allegra).
*Native Tokens*    Related to Native Tokens (Mary).
*Plutus*    Related to Plutus Scripts (Alonzo).
*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**
Needed for conway because of parameterization on era as things like delegation certificates change to support dreps.

**Describe alternatives you've considered**

**Additional context / screenshots**

**Comment by CarlosLopezDeLara** [comment]
Closing in favor of #73
