### ISSUE TITLE
[FR] - Provide JSON schema for input files

### ISSUE THREAD

**Issue by klntsky** [input-output-hk/cardano-cli#593]
**Internal/External**
*External* 

**Area**

*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**
Provide JSON schemas for input/output files.

CLI help messages mention "special JSON schema" for the input files (e.g. [here](https://github.com/IntersectMBO/cardano-cli/blob/3b70e39299b1279c690ec11cb5aec6c84e13eadc/cardano-cli/test/cardano-cli-golden/files/golden/help/conway_transaction_calculate-min-required-utxo.cli#L34
)), but I was unable to find what are these referring to.

Are these files available? What can be done to improve discoverability?

**Comment by carbolymer** [comment]
The help text here is a bit imprecise. It's "detailed metadata schema" and not "special JSON schema". I'll try to find if we have a spec somewhere, but here's an example how it should look like: https://github.com/IntersectMBO/cardano-node/issues/4335#issuecomment-2047984996
I'll put up a PR making the help texts clearer.

**Comment by carbolymer** [comment]
The metadata formats descriptions are here: https://github.com/input-output-hk/cardano-node-wiki/wiki/tx-metadata#metadata-schemas---mappings-and-formats
