### ISSUE TITLE
[FEATURE] - Incorporate the new parameter `minFeeRefScriptsCoinsPerByte`

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#598]
## What
Incorporate the new parameter `minFeeRefScriptsCoinsPerByte` in `action create-protocol-parameters-update` options. 

## Why
This parameter has been just recently added to ledger. https://github.com/IntersectMBO/cardano-ledger/blob/b547c7775e75e78b7bdb73feac7fdd7b920aabef/eras/conway/impl/cddl-files/conway.cddl#L411

## Personas

- [ ] SPOs
- [ ] dApp Devs
- [ ] Exchanges
- [ ] Wallets
- [ ] 3rd party tools
- [x] ADA holders 

## Definition of Done (DoD)

- [ ] [Acceptance Criteria + User Stories & DoD](https://input-output.atlassian.net/wiki/spaces/QA/pages/3584229468/Acceptance+Criteria+DoD) created and singed-off (by PO, dev & test owners)
- [ ] Builds successfully on CI
- [ ] Code & Test review (as per Acceptance Criteria)
- [ ] There is documentation and/or examples for the new functionality (usage/response)
- [ ] Log/record changes on **Vnext** (or similar depending on what we adopt)
- [ ] Ticket number(s) included in PR description
- [ ] All Acceptance Criteria met and covered by dev/unit/property/integration tests
- [ ] System/E2E automated tests + System Test Engineer Owner Sign-off

> **_NOTE:_**  Ideally, we should merge only fully implemented and tested features into the master branch. 
> So all the above steps are required for the PR to be merged.  
> In order to avoid the PRs becoming stale and requiring to be rebased on master, these can be merged 
> after a reasonable time (current agreement is 3 days) if the System Test Engineer Owner's sign-off 
> was not provided (last step in the DoD).

> **_IMPORTANT:_** Any deviation from the plan should be discussed and agreed as a comment in the Feature file. 

## Sign-off

- [ ] Product Owner
- [ ] Dev Owner
- [ ] System Test Engineer Owner

# Related PRs

## Acceptance Criteria

- [ ] The flag is available on `action create-protocol-parameters-update`.
- [ ] When using the flag, the resulting CBOR complies with the conway CDDL.

**Comment by smelc** [comment]
@CarlosLopezDeLara> probably a good one for us to pair program :slightly_smiling_face:

**Comment by smelc** [comment]
We need https://github.com/IntersectMBO/cardano-ledger/commit/b58136ba62dacf8a131e2bdaf9aaaa6c343a4792 released in `cardano-ledger-conway` to do this, and right now it's unreleased. It will be there in 1.13.0 probably.

**Comment by smelc** [comment]
Taking it, as discussed with @CarlosLopezDeLara today.

**Comment by smelc** [comment]
@CarlosLopezDeLara> reassigning to you, as you may have bandwidth again to work with us :tada:

**Comment by smelc** [comment]
There are two steps in this issues:

1. Augment the type `IntroducedInConwayPParams` in `cardano-api`
2. Augment the parser `pIntroducedInConwayPParams` in `cardano-cli`

**Comment by CarlosLopezDeLara** [comment]
Still blocked: 
* https://chap.intersectmbo.org/package/cardano-ledger-conway-1.12.0.0/ is the latest version in CHAP. 
* `minFeeRefScriptsCoinsPerByte` is coming in cardano-ledger-conway 1.13.0.0

**Comment by smelc** [comment]
This shouldn't be blocked anymore since https://chap.intersectmbo.org/package/cardano-ledger-conway-1.13.1.0/ is on CHaP
