### ISSUE TITLE
Inconsistent keyHash query outputs

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-cli#601]
```console
$ cardano-cli version
cardano-cli 8.20.0.0 - linux-x86_64 - ghc-8.10
git rev 4bb2048db77d623ee6e3678618c2d8b6c4676333
```

I just saw, that the output of `conway query drep-stake-distribution` generates an output like:

```json
[
    [
        "drep-keyHash-f37f0e0ab191bdc32179022d8431ae1891a323a7e7c8bd532a76c6fc",
        9994772193
    ],
    [
        "drep-keyHash-fa6a8dc2635dddcf9af495cb144f7eb4ff845866fe48695ad7cb65d3",
        10025824434
    ],
    [
        "drep-keyHash-fd1e9fb13ef9a4bdd0c7e47aef0bfc065eca6c4ac9b613861ccf20cb",
        3566363
    ],
    [
        "drep-alwaysAbstain",
        169703702533
    ],
    [
        "drep-alwaysNoConfidence",
        160978131162
    ]
]
```

but a `conway query stake-address-info` generates a different output for the `voteDelegation` entry:

```json
[
  {
    "address": "stake_test1urqntq4wexjylnrdnp97qq79qkxxvrsa9lcnwr7ckjd6w0cr04y4p",
    "delegationDeposit": 2000000,
    "rewardAccountBalance": 14134097959,
    "stakeDelegation": "pool1rdaxrw3722f0x3nx4uam9u9c6dh9qqd2g83r2uyllf53qmmj5uu",
    "voteDelegation": "keyHash-8f4fefcf28017a57b41517a67d56ef4c0dc04181a11d35178dd53f4c"
  }
]
```

so we should at least have the same `keyHash` output there. or shift to the bech representation `drep1...`

**Comment by smelc** [comment]
@gitmachtl> is there a way for me to reproduce the state with which you generated this output?

Right now if I use `cardano-testnet` it's not super convenient for me, so I would rather reuse your method if I can run it using a custom built `cardano-cli` version (and I suspect that yes, this is possible :wink:).

**Comment by smelc** [comment]
ping @gitmachtl regarding https://github.com/IntersectMBO/cardano-cli/issues/601#issuecomment-2146937070

**Comment by gitmachtl** [comment]
> ping @gitmachtl regarding [#601 (comment)](https://github.com/IntersectMBO/cardano-cli/issues/601#issuecomment-2146937070)

@smelc i think we can leave it as it is tbh. i was not aware of the scriptHash type back in feb and now many tools already adopted the current outputs. its not hurting, and its not really possible to have a bech representation for all those cases. so, i would keep it as it is right now. should i close the issue?

**Comment by smelc** [comment]
@gitmachtl> yes please close the issue then :+1:

**Comment by gitmachtl** [comment]
Not completed, but not important right now.
