### ISSUE TITLE
cardano-cli cannot sign with `ConstitutionalCommittee Cold/Hot ExtendedSigningKey_ed25519_bip32`

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-cli#604]
This issue was marked as solved and merged, but is not working with cardano-cli 8.20.0.0

https://github.com/IntersectMBO/cardano-cli/issues/586

@smelc

**Comment by smelc** [comment]
@mkoura> alas, signing with CC extended keys didn't make it to `8.20.0.0`, it was merged just _after_ the release:

![image](https://github.com/IntersectMBO/cardano-cli/assets/634720/292ef5ea-bcf4-4dc3-a16a-8a7763b5421a)

It will be there in the next release of `cardano-cli`!

**Comment by smelc** [comment]
@mkoura> note we'll release `cardano-cli` soon, to provide you with https://github.com/IntersectMBO/cardano-cli/pull/561 too; so stay tuned :slightly_smiling_face:
