### ISSUE TITLE
Cannot register and delegate Plutus stake address in single tx

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-cli#618]
## Description

An attempt to register and delegate a Plutus stake address in single tx fails on submit with `MissingScriptWitnessesUTXOW`.

This issue can be reproduced on both Babbage and Conway eras.

I'm testing this on node 73f2ec3e0b68886b0916223b41dc5d2a7171f011 with following SRPs:
```
source-repository-package
    type: git
    location: https://github.com/IntersectMBO/cardano-api.git
    tag: dcf9ca6292c356e03c978b3952ba96ff453844e3
    subdir: cardano-api

source-repository-package
    type: git
    location: https://github.com/IntersectMBO/cardano-cli.git
    tag: e1b491bc4259fadc29dabdd0a400e94e4378b50a
    subdir: cardano-cli
```

### Babbage

1. Create stake address registration cert:

> cardano-cli stake-address registration-certificate --stake-script-file cardano_node_tests/tests/data/plutus/v1/guess-42-stake.plutus --out-file "test_delegate_deregister[build_raw-plutus_v1]_ci2_fad_addr0_stake_reg.cert

2. Create stake address delegation cert:

> cardano-cli stake-address delegation-certificate --stake-script-file cardano_node_tests/tests/data/plutus/v1/guess-42-stake.plutus --stake-pool-id pool1zuvv9x8fz7l6hhlsl06enlwldkrsjcp8se449aamx9tw2ut5r7x --out-file "test_delegate_deregister[build_raw-plutus_v1]_ci2_fad_addr0_stake_deleg.cert

3. Build a transaction:

> cardano-cli transaction build-raw --fee 300000 --out-file "test_delegate_deregister[build_raw-plutus_v1]_ci2_fad_reg_deleg_tx.body" --certificate-file "test_delegate_deregister[build_raw-plutus_v1]_ci2_fad_addr0_stake_reg.cert" --certificate-file "test_delegate_deregister[build_raw-plutus_v1]_ci2_fad_addr0_stake_deleg.cert" --certificate-script-file cardano_node_tests/tests/data/plutus/v1/guess-42-stake.plutus --certificate-execution-units "(218855869,686154)" --certificate-redeemer-file cardano_node_tests/tests/data/plutus/42.redeemer --tx-in-collateral "fb5d516a26fd317f75baf73f3bfe58716e6aa989f8752f391378784354bf5260#0" --protocol-params-file pparams-fnrt.json --tx-in "fb5d516a26fd317f75baf73f3bfe58716e6aa989f8752f391378784354bf5260#3" --tx-out "addr_test1yz6xaggap2fd7uf3j8sy623vp5d5su3t956j6j9l8z2we2h49efzcr2v6ktsfjyrcvc00qgnf30spkq49ke7eguxq92qpsgeac+1499300000" --babbage-era

4. Sign the transaction
5. Try to submit the transaction
6. Observe the failure:

> Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (AlonzoInBabbageUtxowPredFailure (ShelleyInAlonzoUtxowPredFailure (MissingScriptWitnessesUTXOW (fromList [ScriptHash "f52e522c0d4cd59704c883c330f781134c5f00d8152db3eca3860154"]))))])

### Conway

1. Create stake address registration cert:

> cardano-cli conway stake-address registration-certificate --key-reg-deposit-amt 400000 --stake-script-file cardano_node_tests/tests/data/plutus/v1/guess-42-stake.plutus --out-file "test_delegate_deregister[build_raw-plutus_v1]_ci1_zfy_addr0_stake_reg.cert

2. Create stake address delegation cert:

> cardano-cli conway stake-address stake-delegation-certificate --stake-script-file cardano_node_tests/tests/data/plutus/v1/guess-42-stake.plutus --stake-pool-id pool1e5un5gtpg9aawwpc7qcufvpwp824zrkdse9nnfj4fnukvc5d6yf --out-file "test_delegate_deregister[build_raw-plutus_v1]_ci1_zfy_addr0_stake_deleg.cert

3. Build a transaction:

> cardano-cli conway transaction build-raw --fee 300000 --out-file "test_delegate_deregister[build_raw-plutus_v1]_ci1_zfy_reg_deleg_tx.body" --certificate-file "test_delegate_deregister[build_raw-plutus_v1]_ci1_zfy_addr0_stake_reg.cert" --certificate-file "test_delegate_deregister[build_raw-plutus_v1]_ci1_zfy_addr0_stake_deleg.cert" --certificate-script-file cardano_node_tests/tests/data/plutus/v1/guess-42-stake.plutus --certificate-execution-units "(218855869,686154)" --certificate-redeemer-file cardano_node_tests/tests/data/plutus/42.redeemer --tx-in-collateral "6fc320aef20c7a5e85ba48c00f935d33482f7a51e00868b418f275a096b0e261#0" --protocol-params-file pparams-jxjg.json --tx-in "6fc320aef20c7a5e85ba48c00f935d33482f7a51e00868b418f275a096b0e261#3" --tx-out "addr_test1yq6ag6zd58lzpvwsxrt6glkss8hdnt6lzg80c26rv9jawm849efzcr2v6ktsfjyrcvc00qgnf30spkq49ke7eguxq92q6vuwkv+1499300000

4. Sign the transaction
5. Try to submit the transaction
6. Observe the failure:

> Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraConway (ApplyTxError [ConwayUtxowFailure (AlonzoInBabbageUtxowPredFailure (ShelleyInAlonzoUtxowPredFailure (MissingScriptWitnessesUTXOW (fromList [ScriptHash "f52e522c0d4cd59704c883c330f781134c5f00d8152db3eca3860154"]))))])

## Additional Context

OS: Fedora 38

Files used for reproduction:

[delegation_issue.tar.gz](https://github.com/IntersectMBO/cardano-cli/files/14375484/delegation_issue.tar.gz)

**Comment by Jimbo4350** [comment]
These are the relevant SRPs

source-repository-package
    type: git
    location: https://github.com/IntersectMBO/cardano-api.git
    tag: 4fafc3e124b5f21d96956343be9870c5b81d2cff
    subdir: cardano-api


source-repository-package
    type: git
    location: https://github.com/IntersectMBO/cardano-cli.git
    tag: f874614706866f0c85059ecf378fd0a80760492d
    subdir: cardano-cli

cardano node at: ac93173ed657dabbeed126424b7888d5fe1cb1fd

**Comment by carbolymer** [comment]
Works for me in babbage, using node's mkfiles.sh
* `env.sh`:
```bash
export TESTNET_DATA_DIR=~/workspace/iohk/cardano-node/example
export CARDANO_NODE_SOCKET_PATH=$TESTNET_DATA_DIR/node-spo1/node.sock
export CARDANO_CLI=$(cabal list-bin cardano-cli)
export CARDANO_NODE=$(cabal list-bin cardano-node)
export CARDANO_NODE_NETWORK_ID=42
```
* `run.sh`
```bash
#!/bin/bash

. ../env.sh
set -euxo pipefail

pool_id=$($CARDANO_CLI query stake-pools | head -1)

$CARDANO_CLI stake-address registration-certificate \
  --stake-script-file ./guess-42-stake.plutus \
  --out-file 'test_delegate_deregister[build_raw-plutus_v1]_ci2_fad_addr0_stake_reg.cert'

$CARDANO_CLI stake-address delegation-certificate \
  --stake-script-file guess-42-stake.plutus \
  --stake-pool-id $pool_id \
  --out-file 'test_delegate_deregister[build_raw-plutus_v1]_ci2_fad_addr0_stake_deleg.cert'

$CARDANO_CLI query protocol-parameters --out-file "pparams-fnrt.json"

address1=$($CARDANO_CLI address build --payment-verification-key-file $TESTNET_DATA_DIR/utxo-keys/utxo1.vkey)

utxo1=$($CARDANO_CLI query utxo --address "$address1" --output-json | jq -r 'keys[0]')

$CARDANO_CLI transaction build-raw \
  --fee 300000 \
  --out-file "test_delegate_deregister[build_raw-plutus_v1]_ci2_fad_reg_deleg_tx.body" \
  --certificate-file "test_delegate_deregister[build_raw-plutus_v1]_ci2_fad_addr0_stake_reg.cert" \
  --certificate-file "test_delegate_deregister[build_raw-plutus_v1]_ci2_fad_addr0_stake_deleg.cert" \
  --certificate-script-file guess-42-stake.plutus \
  --certificate-execution-units "(218855869,686154)" \
  --certificate-redeemer-file 42.redeemer \
  --tx-in-collateral "$utxo1" \
  --protocol-params-file pparams-fnrt.json \
  --tx-in "$utxo1" \
  --tx-out "${address1}+599999700000" \
  --babbage-era

$CARDANO_CLI transaction sign \
  --signing-key-file $TESTNET_DATA_DIR/utxo-keys/utxo1.skey \
  --tx-body-file "test_delegate_deregister[build_raw-plutus_v1]_ci2_fad_reg_deleg_tx.body" \
  --out-file "test_delegate_deregister[build_raw-plutus_v1]_ci2_fad_reg_deleg_tx.body.signed"

$CARDANO_CLI transaction submit --tx-file "test_delegate_deregister[build_raw-plutus_v1]_ci2_fad_reg_deleg_tx.body.signed"

```

**Comment by Jimbo4350** [comment]
Resolved by: https://github.com/IntersectMBO/cardano-api/pull/456
