### ISSUE TITLE
expand cardano-cli conway query drep-state to also query by scripthash

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#621]
Currently, `query drep-state` does **not** support querying by script hash 

```
cardano-cli conway query drep-state [--socket-path SOCKET_PATH]
                                             [--cardano-mode
                                               [--epoch-slots SLOTS]]
                                             [ --mainnet
                                             | --testnet-magic NATURAL
                                             ]
                                             ( --all-dreps
                                             |
                                             ( --drep-verification-key STRING
                                             | --drep-verification-key-file FILE
                                             | --drep-key-hash HASH
                                             )
                                             )
                                             [--include-stake]
                                             [--volatile-tip | --immutable-tip]
                                             [--out-file FILE]
```
We need to add a flag `--drep-script-hash` that allows querying an individual drep that is script based (i.e a multisig drep) so that when running: 

```
cardano-cli conway query drep-state --drep-script-hash eeb006239ad2562556b736c3990f20968fcf89bb6d4f7292aaa0c30a
```
it will return 

```
    [
        {
            "scriptHash": "eeb006239ad2562556b736c3990f20968fcf89bb6d4f7292aaa0c30a"
        },
        {
            "anchor": {
                "dataHash": "54c70f40d9245e9dd8982651233d5234438e26fa3cec5a1c5e90241ab759b1a3",
                "url": "https://hornan7.github.io/dRep-registration.txt"
            },
            "deposit": 2000000,
            "expiry": 271,
            "stake": 9997655226
        }
    ],
```

**Comment by Hornan7** [comment]
If you guys can also add a flag `--drep-script-hash` to allow voting with a drep that is script based (i.e. a multisig drep) when running the command:
```
cardano-cli conway governance vote create
                                (--yes | --no | --abstain)
                                --governance-action-tx-id TXID
                                --governance-action-index WORD32
                                (--drep-verification-key STRING
                                |--drep-verification-key-file FILE
                                |--drep-key-hash HASH
                                |--stake-pool-verification-key STRING
                                |--cold-verification-key-file FILE
                                |--stake-pool-id STAKE_POOL_ID
                                |--cc-hot-verification-key STRING
                                |--cc-hot-verification-key-file FILE
                                |--cc-hot-key-hash STRING
                                )
                                [--anchor-url TEXT
                                  --anchor-data-hash HASH]
                                --out-file FILE
```
I would greatly appreciate it :)

**Comment by palas** [comment]
For the record, this part is now covered by this other issue https://github.com/IntersectMBO/cardano-cli/issues/661

> If you guys can also add a flag `--drep-script-hash` to allow voting with a drep that is script based (i.e. a multisig drep) when running the command:
> 
> ```
> cardano-cli conway governance vote create
>                                 (--yes | --no | --abstain)
>                                 --governance-action-tx-id TXID
>                                 --governance-action-index WORD32
>                                 (--drep-verification-key STRING
>                                 |--drep-verification-key-file FILE
>                                 |--drep-key-hash HASH
>                                 |--stake-pool-verification-key STRING
>                                 |--cold-verification-key-file FILE
>                                 |--stake-pool-id STAKE_POOL_ID
>                                 |--cc-hot-verification-key STRING
>                                 |--cc-hot-verification-key-file FILE
>                                 |--cc-hot-key-hash STRING
>                                 )
>                                 [--anchor-url TEXT
>                                   --anchor-data-hash HASH]
>                                 --out-file FILE
> ```
> 
> I would greatly appreciate it :)
