### ISSUE TITLE
create-testnet-data to support drep delegation and registration

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#629]
Requirement from benchmark(P&T team):  

Injected DReps need to have stake delegated to them (and be registered as a prerequisite).

Currently we have:
```
data GenesisCreateTestNetDataCmdArgs = GenesisCreateTestNetDataCmdArgs
    [...]  
    , numDrepKeys :: !Word -- ^ The number of DRep keys to create. Right now they receive neither delegation nor are registrated. This will come later.
```
Bencmharks run with millions of utxo entries, creating delegation via transaction is not really a good option for them, it would require large number of transactions.  

UPDATE: 

We currently have `stake-delegators` or `transient-stake-delegators`  for writing and not writing stake keys to disk. Some users choose not to write them because they create clusters with millions of entries; while other users do write them because they actualize utilize them on their cluster. 

It would be great to replicate the same behavior for the `drep` keys, probably something like `--drep-keys` and ` --transcient-drep-keys`  so that if you use: 

- `--drep-keys`, the keys are registered and delegated but also written down to disk for future utilization during the benchmark run. Think of the case where the they will load the system with votes in governance actions
- `--transcient-drep-keys` the dreps are registered and the delegation map created but the keys are not written down to disk as these will not be used during the benchmark run

**Comment by smelc** [comment]
Assigning to you @palas, because - as discussed on Slack - you are already on this.

**Comment by palas** [comment]
This is solved by https://github.com/IntersectMBO/cardano-cli/pull/646
