### ISSUE TITLE
Submiting multiple certificates in single TX

### ISSUE THREAD

**Issue by saratomaz** [input-output-hk/cardano-cli#645]
## Description

Failing when submit (de)registration certificates in single TX and check that the order matter.

## Steps to Reproduce
        * create stake address registration cert
        * create stake address deregistration cert
        * register, deregister, register, deregister and register stake address in single TX
        * check that the address is registered

## Additional Context

```
cardano-cli conway transaction build 
--tx-in "0bb4d2b992b8de6413df83248b0bff0897f651c2ea172f14c1f4393e0d08ba35#0" 
--certificate-file "test_addr_registration_certificate_order[build]_ci0_kgf_addr0_stake_reg.cert" 
--certificate-file "test_addr_registration_certificate_order[build]_ci0_kgf_addr0_stake_dereg.cert" 
--certificate-file "test_addr_registration_certificate_order[build]_ci0_kgf_addr0_stake_reg.cert" 
--certificate-file "test_addr_registration_certificate_order[build]_ci0_kgf_addr0_stake_dereg.cert" 
--certificate-file "test_addr_registration_certificate_order[build]_ci0_kgf_addr0_stake_reg.cert" 
--change-address addr_test1qqculf5tdqnlu2gsmjacdy7ztu38kpwcevv78c5jhevgdame97j30x2g8veackte334psj0qjmazngp8q52hk4v9ztfqe0ayl7 
--witness-override 2 
--out-file "test_addr_registration_certificate_order[build]_ci0_kgf_reg_dereg_cert_order_tx.body" 
--testnet-magic 42
```

```
{
    "type": "CertificateConway",
    "description": "Stake Address Registration Certificate",
    "cborHex": "83078200581cd801c9c42cf6bf3b4cb37d3f39aac66ddb89c9595fa4034c9b2924f21a00061a80"
}
```

```
{
    "type": "CertificateConway",
    "description": "Stake Address Deregistration Certificate",
    "cborHex": "83088200581cd801c9c42cf6bf3b4cb37d3f39aac66ddb89c9595fa4034c9b2924f21a00061a80"
}
```

using cardano-node latest master

## Possible Solution

If you have a potential solution to the problem, please describe it here.

**Comment by carbolymer** [comment]
@saratomaz Can you add which cardano-cli version are you using? What error are you getting in result?

**Comment by saratomaz** [comment]
We don't get an error when the transaction is submited, but after, if we check the address using:

`cardano-cli conway query stake-address-info --address  <stake_address>`

nothing is returned

**Comment by saratomaz** [comment]
![image](https://github.com/IntersectMBO/cardano-cli/assets/97231749/e9dbf79d-7abc-4068-80f5-ce871c6e9872)
