### ISSUE TITLE
[FR] - Add a command to obtain the reference script size (in bytes) of a transaction

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-cli#667]
**Internal/External**

*Internal*   

**Area**

*Other*   

**Describe the feature you'd like**

Ledger now requires the reference script sizes to calculate the transaction minimum fee. To obtain the minimum script size, we need the entire UTXO set, which requires querying the node. This means that to implement the [calculate-min-fee](https://github.com/IntersectMBO/cardano-cli/blob/fcd5cf8e53af848703af2396e50bf460c76c92be/cardano-cli/src/Cardano/CLI/EraBased/Run/Transaction.hs#L1012) without it needing to communicate with the node, we need to pass the reference script size in bytes as an extra parameter.  Thus, we need a new CLI command that queries the nodes to obtain this information. 

For reference, [here is](https://github.com/IntersectMBO/cardano-ledger/blob/6764449651dd69be31a1565871975e5c0313e2de/eras/conway/impl/src/Cardano/Ledger/Conway/UTxO.hs#L149) how the reference script size of a transaction is calculated in the ledger.

**Comment by smelc** [comment]
cc @CarlosLopezDeLara
