### ISSUE TITLE
Unexpected output from `calculate-min-required-utxo`

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-cli#685]
## Description

The output of `transaction calculate-min-required-utxo` changed from

```
Lovelace 1060260
```

to

```
Coin 1060260
```

This can break tools and scripts.

## Steps to Reproduce

1. Run
> cardano-cli transaction calculate-min-required-utxo --protocol-params-file pparams.json --babbage-era --tx-out "addr_test1vzyr29zhw54v2wakglywsz2s25cn7echguh4p5nv5e9ey8qqjssay+1 293a0a077ee867bebcbb7fb7e1ab488f7021f65b475b038e11cda250.636f75747473636f696e6d646f69+2000000"

## Additional Context

Tested in Babbage and Conway on cardano-cli 8.21.0.0 and cardano-node 
843059052dfd41b5457864d9ed34f301d2fc6efc

**Comment by smelc** [comment]
This is a consequence of https://github.com/IntersectMBO/cardano-api/pull/475. You will have to adapt your tests @mkoura :pray:

**Comment by mkoura** [comment]
Thanks @smelc Closing as this is an expected change.
