### ISSUE TITLE
[FEATURE] - Create an INFO governance action

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#7]
## What

As an ada holder I want to create an INFO governance action so that I can submit it to the chain.

This build on top of the action command from https://github.com/input-output-hk/cardano-cli/issues/6

It should be something like: 

```
cardano-cli conway governance action create-info
--proposal-url 
--proposal-hash
--proposal-file
--out-file
```
`--metadata-url` expects a url containing the document part of the Info action. 
`--metadata-hash` expects the hash of the document hosted on --metadata-url 
`--out-file` is the path to the action file which we can later use on `build `or `build-raw`to include the action to a transaction body. 
 
## Why

Its one of the 7 governance actions listed on CIP1694. CLI is the primary way to interact with the blockchain

## Personas

- [ ] SPOs
- [ ] dApp Devs
- [ ] Exchanges
- [ ] Wallets
- [ ] 3rd party tools
- [x] ADA holders 

## Definition of Done (DoD)

- [ ] [Acceptance Criteria + User Stories & DoD](https://input-output.atlassian.net/wiki/spaces/QA/pages/3584229468/Acceptance+Criteria+DoD) created and singed-off (by PO, dev & test owners)
- [ ] Builds successfully on CI
- [ ] Code & Test review (as per Acceptance Criteria)
- [ ] There is documentation and/or examples for the new functionality (usage/response)
- [ ] Log/record changes on **Vnext** (or similar depending on what we adopt)
- [ ] Ticket number(s) included in PR description
- [ ] All Acceptance Criteria met and covered by dev/unit/property/integration tests
- [ ] System/E2E automated tests + System Test Engineer Owner Sign-off

> **_NOTE:_**  Ideally, we should merge only fully implemented and tested features into the master branch. 
> So all the above steps are required for the PR to be merged.  
> In order to avoid the PRs becoming stale and requiring to be rebased on master, these can be merged 
> after a reasonable time (current agreement is 3 days) if the System Test Engineer Owner's sign-off 
> was not provided (last step in the DoD).

> **_IMPORTANT:_** Any deviation from the plan should be discussed and agreed as a comment in the Feature file. 

## Sign-off

- [ ] Product Owner
- [ ] Dev Owner
- [ ] System Test Engineer Owner

# Related PRs

1.  https://github.com/input-output-hk/cardano-cli/pull/292

**Comment by smelc** [comment]
Hey @CarlosLopezDeLara, I'm not sure how to understand the description:

> ```
> cardano-cli conway governance action create-info
> --proposal-url 
> --proposal-hash
> --proposal-file
> --out-file
> ```
> `--metadata-url` expects a url containing the document part of the Info action. 
> `--metadata-hash` expects the hash of the document hosted on --metadata-url 
> `--out-file` is the path to the action file which we can later use on `build `or `build-raw`to include the action to a transaction body. 

The `--help` snippet lists 4 parameters to `create-info`, but then you describe three of them in the text that follows and they have slightly different names (e.g. _proposal_ versus _metadata_).

Could you detail a bit more?

**[edit] Was clarified on Slack: [discussion](https://input-output-rnd.slack.com/archives/C031GFLC3DF/p1695152376927549?thread_ts=1695127418.435279&cid=C031GFLC3DF)**

**Comment by CarlosLopezDeLara** [comment]
resolved in https://github.com/input-output-hk/cardano-cli/pull/292
