### ISSUE TITLE
Error when running the node

### ISSUE THREAD

**Issue by Gor-Solomon** [input-output-hk/cardano-cli#703]
## Description

Cardano-node run is failing on windows

## Steps to Reproduce

1. Open power shell (Run as addmin).
2. Switch to the directory where you have installed the cardano node.
3. write the following command: cardano-node run --topology "share\mainnet\topology.json" --database-path "db" --socket-path "\\.\\pipe\cardano" --host-addr 185.215.55.84 --port 3001 --config "share\mainnet\config.json"
4. Hit enter
5. See how many errors are happenning.

[DESKTOP-:cardano.node.PeerSelection:Info:55] [2024-04-06 19:08:15.21 UTC] TracePublicRootsRequest 100 0
[DESKTOP-:cardano.node.DiffusionInitializationTracer:Info:49] [2024-04-06 19:08:15.21 UTC] ConfiguringServerSocket 185.215.55.84:3001
[DESKTOP-:cardano.node.PublicRootPeers:Info:59] [2024-04-06 19:08:15.21 UTC] TracePublicRootRelayAccessPoint (fromList [(RelayAccessDomain "preprod-node.play.dev.cardano.org" 3001,DoNotAdvertisePeer)])
[DESKTOP-:cardano.node.PeerSelection:Error:55] [2024-04-06 19:08:15.21 UTC] TraceOutboundGovernorCriticalFailure AsyncCancelled
[DESKTOP-:cardano.node.ConnectionManager:Info:49] [2024-04-06 19:08:15.22 UTC] TrShutdown
[DESKTOP-:cardano.node.LocalInboundGovernor:Error:57] [2024-04-06 19:08:15.22 UTC] TrInboundGovernorError AsyncCancelled
[DESKTOP-:cardano.node.LocalServer:Critical:58] [2024-04-06 19:08:15.22 UTC] TrServerError AsyncCancelled
[DESKTOP-:cardano.node.LocalServer:Notice:56] [2024-04-06 19:08:15.22 UTC] TrServerStopped
[DESKTOP-:cardano.node.LocalConnectionManager:Info:51] [2024-04-06 19:08:15.22 UTC] TrShutdown
[DESKTOP-:cardano.node.DiffusionInitializationTracer:Critical:3] [2024-04-06 19:08:15.22 UTC] DiffusionErrored Network.Socket.bind: failed (Cannot assign requested address (WSAEADDRNOTAVAIL))
[DESKTOP-:cardano.node.ChainDB:Info:3] [2024-04-06 19:08:15.22 UTC] Closed Immutable DB.
[DESKTOP-:cardano.node.ChainDB:Info:3] [2024-04-06 19:08:15.22 UTC] Closed db with immutable tip at genesis (origin) and tip 9ad7ff320c9cf74e0f5ee78d22a85ce42bb0a487d0506bf60cfb5a91ea4497d2 at slot 0

## Additional Context

Windows 10

![image](https://github.com/IntersectMBO/cardano-cli/assets/24508169/dafa2178-a3d4-4a08-9292-f7778b14f94b)

With this exception message when closing it:

![image](https://github.com/IntersectMBO/cardano-cli/assets/24508169/a70c267f-9083-409f-b4e7-8bf33af7de6f)

**Comment by carbolymer** [comment]
Looks like it's coming from somewhere here https://github.com/lhmouse/mcfgthread/blob/5e1018e158ab45a150b25c68009ecc2867f68b6f/src/env/tls.c#L46

**Comment by Jimbo4350** [comment]
Please move this issue to [cardano-node](https://github.com/IntersectMBO/cardano-node). This does not belong in the cardano-cli repo.
