### ISSUE TITLE
[FEATURE] - Update transaction view command so that it shows proposals and votes inside the transaction. 

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#711]
## What

Update transaction view command so that it shows votes inside the transaction. 

## Why
On a setup where there is several individuals involved in witnessing a transactions that contain votes or proposals, each individual wants to verify that the transaction body contains the right proposal/vote. 

## Personas

- [x] DRep
- [x]  CC member
- [x] SPOs
- [ ] dApp Devs
- [ ] Exchanges
- [ ] Wallets
- [ ] 3rd party tools
- [ ] ADA holders 

## Definition of Done (DoD)

- [ ] [Acceptance Criteria + User Stories & DoD](https://input-output.atlassian.net/wiki/spaces/QA/pages/3584229468/Acceptance+Criteria+DoD) created and singed-off (by PO, dev & test owners)
- [ ] Builds successfully on CI
- [ ] Code & Test review (as per Acceptance Criteria)
- [ ] There is documentation and/or examples for the new functionality (usage/response)
- [ ] Log/record changes on **Vnext** (or similar depending on what we adopt)
- [ ] Ticket number(s) included in PR description
- [ ] All Acceptance Criteria met and covered by dev/unit/property/integration tests
- [ ] System/E2E automated tests + System Test Engineer Owner Sign-off

> **_NOTE:_**  Ideally, we should merge only fully implemented and tested features into the master branch. 
> So all the above steps are required for the PR to be merged.  
> In order to avoid the PRs becoming stale and requiring to be rebased on master, these can be merged 
> after a reasonable time (current agreement is 3 days) if the System Test Engineer Owner's sign-off 
> was not provided (last step in the DoD).

> **_IMPORTANT:_** Any deviation from the plan should be discussed and agreed as a comment in the Feature file. 

## Sign-off

- [ ] Product Owner
- [ ] Dev Owner
- [ ] System Test Engineer Owner

# Related PRs

1.  PR # here

## Acceptance Criteria

Acceptance Criteria & User Stories define here (or in a separate file (linked here) for a big feature)

Example - https://github.com/input-output-hk/cardano-node/issues/4453

**Comment by smelc** [comment]
Reproduction procedure: `cabal run cardano-cli -- conway transaction view --tx-file pv3.tx.raw` with `pv3.tx.raw` being:

```json
{
    "type": "Unwitnessed Tx ConwayEra",
    "description": "Ledger Cddl Format",
    "cborHex": "84a400d9010281825820ec5681a833819aa9c337526d89d68d0a5ce14ed970d453ad9870276a01dd862c0001818258390062573d3d7e30dc551b41fc1e11a9558cba6d0b7b179057aa55963c4208f121b36abf2bcdd7daa2551c1e6653413a78c419e170d3319924d31b0000000ba4384edf021a0003252114d9010281841b0000000ba43b7400581de008f121b36abf2bcdd7daa2551c1e6653413a78c419e170d3319924d38400f6a112a1029f1a0003236119032c01011903e819023b00011903e8195e7104011903e818201a0001ca761928eb041959d818641959d818641959d818641959d818641959d818641959d81864186418641959d81864194c5118201a0002acfa182019b551041a000363151901ff00011a00015c3518201a000797751936f404021a0002ff941a0006ea7818dc0001011903e8196ff604021a0003bd081a00034ec5183e011a00102e0f19312a011a00032e801901a5011a0002da781903e819cf06011a00013a34182019a8f118201903e818201a00013aac0119e143041903e80a1a00030219189c011a00030219189c011a0003207c1901d9011a000330001901ff0119ccf3182019fd40182019ffd5182019581e18201940b318201a00012adf18201a0002ff941a0006ea7818dc0001011a00010f92192da7000119eabb18201a0002ff941a0006ea7818dc0001011a0002ff941a0006ea7818dc0001011a0011b22c1a0005fdde00021a000c504e197712041a001d6af61a0001425b041a00040c660004001a00014fab18201a0003236119032c010119a0de18201a00033d7618201979f41820197fb8182019a95d1820197df718201995aa18201a0218f4f50a1a0374f693194a1f0a1a0254f375197e040a1959d818641959d818641a000cb528121a0030f786061a00050ebb011a03eef01c195a39121a0001be42121a05a0543f1a00015414121a00fa8cf9121a0020be0618241a0039e9910c1a000d90bf011a0c2c69e2195ae718241a0001f88d18241a0b52d4be1a00014f8e18241a01f7bc8018241a17272ce0011a17f44a4118481a002392f318481a001d6af61a0001425b041a0001ca761928eb041a0013b72b195f95184a00011a000e48dd19c1c118ed0001fff682785968747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6361726c6f736c6f64656c61722f70726f706f73616c732f6d61696e2f7768792d706c7574757376332d636f73746d6f64656c2e747874582016ffc0c69f7b6aa066ca90b66d887072cb2eb4e9bef01fdbbc1ef9cccec407a9a0f5f6"
}
```

Output is:

```json
{
    "auxiliary scripts": null,
    "certificates": null,
    "collateral inputs": [],
    "era": "Conway",
    "fee": "206113 Lovelace",
    "inputs": [
        "ec5681a833819aa9c337526d89d68d0a5ce14ed970d453ad9870276a01dd862c#0"
    ],
    "metadata": null,
    "mint": null,
    "outputs": [
        {
            "address": "addr_test1qp39w0fa0ccdc4gmg87puydf2kxt5mgt0vteq4a22ktrcssg7ysmx64l90xa0k4z25wpuejngya833qeu9cdxvveynfscsskf5",
            "address era": "Shelley",
            "amount": {
                "lovelace": 49999793887
            },
            "network": "Testnet",
            "payment credential key hash": "62573d3d7e30dc551b41fc1e11a9558cba6d0b7b179057aa55963c42",
            "reference script": null,
            "stake reference": {
                "stake credential key hash": "08f121b36abf2bcdd7daa2551c1e6653413a78c419e170d3319924d3"
            }
        }
    ],
    "redeemers": {},
    "reference inputs": [],
    "required signers (payment key hashes needed for scripts)": null,
    "return collateral": null,
    "total collateral": null,
    "update proposal": null,
    "validity range": {
        "lower bound": null,
        "upper bound": null
    },
    "withdrawals": null,
    "witnesses": []
}
```

which omits governance information there is in this transaction.

**Comment by smelc** [comment]
Here is the concerned call stack:

1. https://github.com/IntersectMBO/cardano-cli/blob/main/cardano-cli/src/Cardano/CLI/EraBased/Run/Transaction.hs#L1447
2. https://github.com/IntersectMBO/cardano-cli/blob/main/cardano-cli/src/Cardano/CLI/Read.hs#L551
3. https://github.com/IntersectMBO/cardano-cli/blob/main/cardano-cli/src/Cardano/CLI/Read.hs#L1035
4. https://github.com/IntersectMBO/cardano-api/blob/main/cardano-api/internal/Cardano/Api/SerialiseLedgerCddl.hs#L301 with `ttoken` being `Unwitnessed Tx ConwayEra`
5. https://github.com/IntersectMBO/cardano-api/blob/main/cardano-api/internal/Cardano/Api/SerialiseLedgerCddl.hs#L166
6. https://github.com/IntersectMBO/cardano-api/blob/main/cardano-api/internal/Cardano/Api/SerialiseLedgerCddl.hs#L199
7. https://github.com/IntersectMBO/cardano-api/blob/main/cardano-api/internal/Cardano/Api/SerialiseCBOR.hs#L26
8. https://github.com/IntersectMBO/cardano-ledger/blob/master/eras/byron/ledger/impl/src/Cardano/Chain/UTxO/Tx.hs#L113 (probably?)

[edit] This went too far on the CDDL path. The crux was JSON serialization, see https://github.com/IntersectMBO/cardano-cli/pull/774

**Comment by smelc** [comment]
Output of `cabal run cardano-cli -- conway transaction view --tx-file pv3.tx.raw`, as of a2873b3225582ba3524cc52c8492a41afc47887b:

```json
{
    "auxiliary scripts": null,
    "certificates": null,
    "collateral inputs": [],
    "era": "Conway",
    "fee": "206113 Lovelace",
    "governance actions": [
        {
            "anchor": {
                "dataHash": "16ffc0c69f7b6aa066ca90b66d887072cb2eb4e9bef01fdbbc1ef9cccec407a9",
                "url": "https://raw.githubusercontent.com/carloslodelar/proposals/main/why-plutusv3-costmodel.txt"
            },
            "deposit": 50000000000,
            "governance action": {
                "contents": [
                    null,
                    {
                        "costModels": ...
                    },
                    null
                ],
                "tag": "ParameterChange"
            },
            "return address": {
                "credential": {
                    "keyHash": "08f121b36abf2bcdd7daa2551c1e6653413a78c419e170d3319924d3"
                },
                "network": "Testnet"
            }
        }
    ],
    "inputs": [
        "ec5681a833819aa9c337526d89d68d0a5ce14ed970d453ad9870276a01dd862c#0"
    ],
    "metadata": null,
    "mint": null,
    "outputs": [
        {
            "address": "addr_test1qp39w0fa0ccdc4gmg87puydf2kxt5mgt0vteq4a22ktrcssg7ysmx64l90xa0k4z25wpuejngya833qeu9cdxvveynfscsskf5",
            "address era": "Shelley",
            "amount": {
                "lovelace": 49999793887
            },
            "network": "Testnet",
            "payment credential key hash": "62573d3d7e30dc551b41fc1e11a9558cba6d0b7b179057aa55963c42",
            "reference script": null,
            "stake reference": {
                "stake credential key hash": "08f121b36abf2bcdd7daa2551c1e6653413a78c419e170d3319924d3"
            }
        }
    ],
    "redeemers": {},
    "reference inputs": [],
    "required signers (payment key hashes needed for scripts)": null,
    "return collateral": null,
    "total collateral": null,
    "update proposal": null,
    "validity range": {
        "lower bound": null,
        "upper bound": null
    },
    "votes": {},
    "withdrawals": null,
    "witnesses": []
}
```
