### ISSUE TITLE
[FR] - `--reference-script-size INT` should be optional and `defaultValue=0`

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-cli#719]
With cardano-cli 8.22+, a new parametere was introduced in the `transaction calculate-min-fee` command. 

Can we please make this an optional parameter which defaults to 0 if not used?

This would make it backwards compatible without breaking changes for just normal transactions. The value for the reference script size comes only into play with SCs. But it would be good to just default it to 0 for normal transactions imo. 

Transactions involing SCs needs special care out of its nature.

Best regards, Martin

**Comment by carbolymer** [comment]
Fixed in https://github.com/IntersectMBO/cardano-cli/pull/716
