### ISSUE TITLE
[FR] - Restructure CLI commands to put the era as the top-level command group

### ISSUE THREAD

**Issue by newhoggy** [input-output-hk/cardano-cli#73]
*Internal*

**Area**
CLI command structure

**Describe the feature you'd like**

Restructure `cardano-cli` so that the era is the highest level command group.  So we have

```
cardano-cli babbage transaction build
cardano-cli conway transaction build
cardano-cli current transaction build
```

instead of:

```
cardano-cli transaction build --babbage-era
cardano-cli transaction build --conway-era
cardano-cli transaction build
```

because `optparse-applicative` does not allow us a good way to hide/show flags based on other flags.
The structure would mean that when someone types `cardano-cli conway governance` they would get all the `CIP-1694` commands in the help, but if they type `cardano-cli babbage governance`, the help is uncluttered with `CIP-1694` commands because they don't make sense in that era.

**Comment by Jimbo4350** [comment]
What about just having `cardano-cli transaction build` as the current era by default?
