### ISSUE TITLE
create-testnet-data: add options from create-cardano

### ISSUE THREAD

**Issue by smelc** [input-output-hk/cardano-cli#764]
We want to add options for `activeSlotsCoeff`, `securityParam`, `slotLength` and populates the genesis with these as well as `epochLength` (derived from the others).

Discussed on Slack [here](https://input-output-rnd.slack.com/archives/G011N23CEAE/p1715652319682029?thread_ts=1715651721.493559&cid=G011N23CEAE).

**Comment by carbolymer** [comment]
[I'm not sure if that's the direction we want](https://github.com/IntersectMBO/cardano-node/pull/5818#discussion_r1584712918). cc: @Jimbo4350

**Comment by smelc** [comment]
Closing, because of https://github.com/IntersectMBO/cardano-cli/issues/764#issuecomment-2115465067
