### ISSUE TITLE
Move conway governance hash  to conway hash 

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#782]
The hash command needs to be moved one level up in the tree, so that it is not inside governance, but instead just in the top level.

**Comment by smelc** [comment]
@CarlosLopezDeLara> what about `conway governance hash script` then? If we move `hash anchor-data` out of `governance`, `conway governance hash script` will be alone in its category. See here:

https://github.com/IntersectMBO/cardano-cli/blob/fed71b38b5935a0a0e4420aaaab7afa503a25a49/cardano-cli/test/cardano-cli-golden/files/golden/help/conway_governance_hash.cli

**Comment by CarlosLopezDeLara** [comment]
@smelc my bad, I should have written "move 'governance hash' one level up.  This is, it can be a more general purpose command rather than specific to governance. 

So the end goal is

`cardano-cli conway hash (anchor-data | script)
`
instead of 

`cardano-cli conway governance hash (anchor-data | script)
`  
Im updating the description
