### ISSUE TITLE
Same help text for key-gen-cold and key-gen-hot for governance committee subcommand.

### ISSUE THREAD

**Issue by nabinpkl** [input-output-hk/cardano-cli#794]
## Description

It is not a bug but an inaccurate description of a subcommand key-gen-hot for the governance committee subcommand.

## Steps to Reproduce
CLI Version
```
cardano-cli 8.23.1.0 - darwin-aarch64 - ghc-8.10
git rev 43149909fc4942e93e14a2686826543a2d9432bf
```

1. Run `cardano-cli conway governance committee`
2. Output help text contains the same description for both.
...

## Additional Context

![image](https://github.com/IntersectMBO/cardano-cli/assets/18091631/4d196051-28ff-468a-b6ce-a25734ac30b0)

## Possible Solution

It should be Create a hot key pair ...

**Comment by smelc** [comment]
@nabinpkl> thanks for your report :heart_hands: We'll fix it soon.

I am moved seeing that you run `cardano-cli` on `darwin-aarch64` since we typically have lots of trouble generating this binary :slightly_smiling_face: Out of curiosity, do you compile it yourself?

**Comment by nabinpkl** [comment]
> I am moved seeing that you run `cardano-cli` on `darwin-aarch64` since we typically have lots of trouble generating this binary 🙂 Out of curiosity, do you compile it yourself?

No, I used the cardano-cli provided on the nix environment.
