### ISSUE TITLE
Missing --hot-script-hash option on governance committee create-hot-key-authorization-certificate subcommand.

### ISSUE THREAD

**Issue by nabinpkl** [input-output-hk/cardano-cli#803]
## Description

It's not a bug per se, but it might be missing here. Even though we can use the `--hot-script-file` option to do the same. But to be consistent across other commands providing a `--hot-script-hash HASH` would complete the missing feature from CLI.

## Steps to Reproduce
CLI Version
```
cardano-cli 8.24.0.0 - linux-x86_64 - ghc-9.4
git rev 0e085e6ebd5ede10e9c84c1cb106bd9639aab3e8
```

1. Run `cardano-cli conway governance committee create-hot-key-authorization-certificate `
2. `--hot-script-hash HASH` option seems to be missing.
...

## Additional Context
![image](https://github.com/IntersectMBO/cardano-cli/assets/18091631/838e59ac-f33d-4618-8df9-fee0fe6b6445)

## Possible Solution
Add a missing option --hot-script-hash HASH Committee hot Native or Plutus script file hash
                           (hex-encoded). Obtain it with "cardano-cli conway
                           governance hash script ...".

**Comment by smelc** [comment]
cc @CarlosLopezDeLara If you confirm this is relevant, I can take it.

**Comment by CarlosLopezDeLara** [comment]
> cc @CarlosLopezDeLara If you confirm this is relevant, I can take it.

Yes, please. It makes sense.
