### ISSUE TITLE
[FR] - Support aarch64-linux in Nix Flake

### ISSUE THREAD

**Issue by sempruijs** [input-output-hk/cardano-cli#805]
External

Area
Regarding the build system outputs

Describe the feature you'd like
I would like to build cardano-cli on aarch64-linux via the nix flake.
I use aarch64-linux in a virtual machine on my mac and raspberry pi is also aarch64-linux.
Here's what I would like to do:

nix build github:intersectmbo/cardano-node#packages.aarch64-linux.cardano-cli
Describe alternatives you've considered

I think you can build it on aarch64-linux but as far I know not via the nix flake.
If I'm missing something please let me know.

**Comment by carbolymer** [comment]
Related comment and PR: https://github.com/IntersectMBO/cardano-cli/pull/686#issuecomment-2033090278

**Comment by carbolymer** [comment]
>I use aarch64-linux in a virtual machine

Do you need to build on aarch64-linux natively, or a cross-compilation to aarch64-linux would 
be sufficient? We have a PR enabling cross-compilation to that architecture - does that work for you: https://github.com/IntersectMBO/cardano-cli/pull/819 ?

**Comment by sempruijs** [comment]
I need it natively. I want to use my raspi 5 as an airgaped machine. I have nix installed on it and when cardano-cli has a new update I could move the files of this repository via a usb stick on my pi and compile the new version. If someone has a better alternative to work around this I'll would love to hear it.
Using nix build blablabla is way easier for me then manually installing all sorts of tools because of my visual impairment.

**Comment by smelc** [comment]
Reopening because #819 introduced production of `aarch64-linux` binaries (via cross compilation), but it's still not supported by the flake (which is what this issue is about).
