### ISSUE TITLE
Build cmd is populating currentTreasuryValue on every TX. It should not. 

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#825]
## Description

 In Conway era, CLI build is populating the field `current treasury value` on every transaction body. This is problematic. Its causes Plutus V1/V2  transactions to fail with `CurrentTreasuryFieldNotSupported` . Ledger expects that field to be empty on such transactions. it can only be not null on PlutusV3. 

It can also be problematic at epoch boundaries for normal transactions. i.e. when the transaction is generated on one epoch and submitted on the next.

See https://github.com/IntersectMBO/cardano-ledger/issues/4470
and https://input-output-rnd.slack.com/archives/CCRB7BU8Y/p1720120358499899

...

## Possible Solution

We should only populate this field when it is strictly needed. i.e. only on treasury donations (I think that is the only time the field is needed).

Have users do a two step process for this query treasury -> build so that the field is only used when strictly necesary and left empty most of the time.

**Comment by smelc** [comment]
So for `transaction build`, sure we can only include the treasury value when a donation is being made.

For `transaction build-raw`, @CarlosLopezDeLara> should we join the parser of the flag for the current treasury value and the parser of the flag for the treasury donation? (So they can either be passed BOTH or none at all). I guess yes, right?

**Comment by smelc** [comment]
Work being done at https://github.com/IntersectMBO/cardano-cli/tree/smelc/tx-build-no-donation-then-no-current-treasury-value
