### ISSUE TITLE
[FR] - Change versioning back to `major.minor.patch`

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-cli#834]
Not sure why this started in first place, but can we go back to versioning of just x.y.z ?

Is there a reason we see version bumps like 9.0.0.0 to 9.0.0.1?

Normally its `major.minor.patch` version, so not sure why we need a "sub-bugfix" number and can't go back to semantic versioning?

Martin

**Comment by smelc** [comment]
cc @Jimbo4350

**Comment by carbolymer** [comment]
We're following the versioning process described here: https://github.com/IntersectMBO/cardano-api/blob/main/RELEASING.md#version-bumping
Tl;dr: In our case it's `cardano-node-major-version.major.minor.patch`.

**Comment by gitmachtl** [comment]
ok, hmm. than why is the node still `major.minor.patch` ?

not 100% why we need to distinguish between those two:
* 8.4.1.3 - if there are only backwards-compatible bug-fixes
* 8.4.2.0 - if there are only backwards-compatible features or bug-fixes

if they are both backwards-compatible

**Comment by smelc** [comment]
@gitmachtl> just FYI there is a cultural thing going on here, that Haskell has its own versioning policy called [PVP](https://pvp.haskell.org/). I personally believe this is a mistake that the Haskell ecosystem is doing, we should use semver but :shrug:
