### ISSUE TITLE
[FR] - Provide governance query for stake distribution

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-cli#850]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Token Locking*    Related to Token Locking (Allegra).
*Native Tokens*    Related to Native Tokens (Mary).
*Plutus*    Related to Plutus Scripts (Alonzo).
*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**
This is provided by consensus in: Added `GetSPOStakeDistr` query. We need to provide a governance query to get this data for end users using CLI.

**Describe alternatives you've considered**

**Additional context / screenshots**

**Comment by palas** [comment]
Still more PRs to merge
