### ISSUE TITLE
Changed error messages for SPO poll commands

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-cli#87]
## Description

The poll commands provided user friendly error messages. These are now replaced by more cryptic ones:

* `GovernanceCmdPollOutOfBoundAnswer 1` instead of `Poll answer out of bounds ...`
* `GovernanceCmdVerifyPollError ErrGovernancePollUnauthenticated` instead of `Signatories MUST be specified as extra signatories on the transaction and cannot be mere payment keys`

**Comment by carbolymer** [comment]
Work started in https://github.com/input-output-hk/cardano-cli/pull/84/
