### ISSUE TITLE
[FEATURE] - Implement `conway query proposals` 

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#903]
## What
The new query `GetProposals` is available in consensus. 
Implement `cardano-cli conway query proposals` on the CLI 

## Why
Will reduce the overhead of the current alternative `cardano-cli conway query gov-state | jq .proposals`

## Personas

- [x] CC members
- [x] DREPS
- [x] SPOs
- [ ] dApp Devs
- [ ] Exchanges
- [ ] Wallets
- [ ] 3rd party tools
- [x] ADA holders 

## Definition of Done (DoD)

- [ ] [Acceptance Criteria + User Stories & DoD](https://input-output.atlassian.net/wiki/spaces/QA/pages/3584229468/Acceptance+Criteria+DoD) created and singed-off (by PO, dev & test owners)
- [ ] Builds successfully on CI
- [ ] Code & Test review (as per Acceptance Criteria)
- [ ] There is documentation and/or examples for the new functionality (usage/response)
- [ ] Log/record changes on **Vnext** (or similar depending on what we adopt)
- [ ] Ticket number(s) included in PR description
- [ ] All Acceptance Criteria met and covered by dev/unit/property/integration tests
- [ ] System/E2E automated tests + System Test Engineer Owner Sign-off

> **_NOTE:_**  Ideally, we should merge only fully implemented and tested features into the master branch. 
> So all the above steps are required for the PR to be merged.  
> In order to avoid the PRs becoming stale and requiring to be rebased on master, these can be merged 
> after a reasonable time (current agreement is 3 days) if the System Test Engineer Owner's sign-off 
> was not provided (last step in the DoD).

> **_IMPORTANT:_** Any deviation from the plan should be discussed and agreed as a comment in the Feature file. 

## Sign-off

- [ ] Product Owner
- [ ] Dev Owner
- [ ] System Test Engineer Owner

# Related PRs

1.  PR # here

## Acceptance Criteria
 
- The query returns all active proposals

- The implemented command output is equivalent to:
`cardano-cli conway query gov-state | jq .proposals`

**Comment by smelc** [comment]
Unstale. This is actively being worked on: 

* https://github.com/IntersectMBO/cardano-api/pull/684
* https://github.com/IntersectMBO/cardano-cli/commits/smelc/cl/implement-query-proposals/
* https://github.com/IntersectMBO/cardano-node/commits/smelc/test-query-proposals
