### ISSUE TITLE
Reduce duplication in Commands/Query.hs

### ISSUE THREAD

**Issue by smelc** [input-output-hk/cardano-cli#983]
While working on `query proposals`, I noticed that many many fields are duplicated in a number of records in https://github.com/IntersectMBO/cardano-cli/blob/82160245479ff2e0c89d1d75f16fb39902aef466/cardano-cli/src/Cardano/CLI/EraBased/Commands/Query.hs#L85

This issue keeps track of sharing all these fields in a nested record.

**Comment by carbolymer** [comment]
I'm not sure that would be a big improvement here. So instead of punning:
```haskell
QueryStakeAddressInfoCmdArgs{ nodeSocketPath, consensusModeParams, networkId, mOutfile}
```
I imagine you'd do something like
```haskell
QueryStakeAddressInfoCmdArgs{ onlineCmdArgs=OnlineCmdArgs{ nodeSocketPath, consensusModeParams, networkId, mOutfile}}
```
which adds more characters and some indirection. We would save some duplication on parsers though. 

I'm not blocking this, just my two cents. I'm ok with trying to do it. 👍🏻
